### ISSUE TITLE
Missing ErrorResponse

### ISSUE THREAD

**Issue by Bungeefan** [DV8FromTheWorld/JDA#1072]
## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report
Missing ErrorResponse enum 400 Maximum number of channels in category reached (50)

### Expected Behavior
Should be in enum in ErrorResponse and maybe add a constant to check this in future times before sending to discord

### Code Example or Reproduction Steps

Create a Channel in a Category with 50 channels in it.

### Exception or Error

```
[ForkJoinPool.commonPool-worker-3] ERROR net.dv8tion.jda.api.requests.RestAction - RestAction queue returned failure: [ErrorResponseException] 400: {"parent_id":["Maximum number of channels in category reached (50)"]}
net.dv8tion.jda.api.exceptions.ContextException: null
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:52) ~[PartnerBot.jar:?]
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:62) ~[PartnerBot.jar:?]
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:168) ~[PartnerBot.jar:?]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:303) ~[PartnerBot.jar:?]
        at tk.bungeefan.bot.commands.Ticket.lambda$openTicket$6(Ticket.java:74) ~[PartnerBot.jar:?]
        at tk.bungeefan.bot.commands.Ticket.openTicket(Ticket.java:92) ~[PartnerBot.jar:?]
        at tk.bungeefan.bot.listener.TicketListener.lambda$onGuildMessageReactionAdd$0(TicketListener.java:42) ~[PartnerBot.jar:?]
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:83) ~[PartnerBot.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
```

**Comment by MinnDevelopment** [comment]
This wouldn't fit into the `ErrorResponse` enum because its not one of those errors. The 400 is the HTTP code rather than a code for the error. The usual format for those responses is `{"code": 50007, "message": "..."}` while this one is `{"parent_id":["Maximum number of channels in category reached (50)"]}`. We can't add any enum constant for this because its in the wrong format so this is intended behavior.
