### ISSUE TITLE
JDA Builder not found but it is in the JAR File

### ISSUE THREAD

**Issue by Seblofs** [DV8FromTheWorld/JDA#1083]
![image](https://user-images.githubusercontent.com/40692731/62868937-0d818400-bd17-11e9-94d6-b4cdc995a64f.png)
like you can see here JDA is in the JAR but on my vserver a error cames when i try to start my jar file: 
```
λ java -jar -Xmx1024M KeksBot.jar
Exception in thread "main" java.lang.NoClassDefFoundError: net/dv8tion/jda/core/JDABuilder
        at core.Main.main(Main.java:21)
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.core.JDABuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
