### ISSUE TITLE
Got this error in my console today.

### ISSUE THREAD

**Issue by tuxnull** [DV8FromTheWorld/JDA#1088]
```
JSONObject["embeds"] not found.
        MESSAGE_UPDATE -> {"flags":1,"guild_id":"432297144763023374","id":"615111724881674241","channel_id":"514861306189316108"}
org.json.JSONException: JSONObject["embeds"] not found.
        at org.json.JSONObject.get(JSONObject.java:471)
        at org.json.JSONObject.getJSONArray(JSONObject.java:618)
        at net.dv8tion.jda.core.handle.MessageUpdateHandler.handleMessageEmbed(MessageUpdateHandler.java:178)
        at net.dv8tion.jda.core.handle.MessageUpdateHandler.handleInternally(MessageUpdateHandler.java:81)
```

told me to report this to the devs so im posting it here

**Comment by MinnDevelopment** [comment]
This is fixed in [4.0.0_43](https://ci.dv8tion.net/job/JDA/43/changes) and can be ignored in v3. Please use the templated issues in the future.
