### ISSUE TITLE
[Fatal] [JDA]: One of the EventListeners had an uncaught exception

### ISSUE THREAD

**Issue by superthread** [DV8FromTheWorld/JDA#114]
Cannot get my simple ping bot to work~
getting the following errors

`[21:55:03] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[21:55:03] [Fatal] [JDA]: Encountered an exception:
java.lang.NullPointerException
	at Commands.PingCommand.action(PingCommand.java:19)
	at Bot1.handleCommand(Bot1.java:41)
	at BotListener.onMessageReceived(BotListener.java:13)
	at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:176)
	at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:57)
	at net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:65)
	at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:545)
	at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:296)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)`

**Comment by jagrosh** [comment]
The null pointer exception is in your own code. Can you upload that class to hastebin? I don't think this is a JDA issue.

**Comment by DV8FromTheWorld** [comment]
Yeah, this doesn't look to be a JDA issue. provide the PingCommand class on http://hastebin.com please.

**Comment by superthread** [comment]
http://hastebin.com/uhotuxawom.java

**Comment by jagrosh** [comment]
In the code you shared, line 19 is blank

Also, MessageReceivedEvent#getTextChannel() can be null if the message was a Direct/Private message

**Comment by superthread** [comment]
sorry, re-ran it and now it's saying line 16 rather than 19

**Comment by jagrosh** [comment]
That will throw a NPE whenever the bot gets a private message

**Comment by superthread** [comment]
@jagrosh what's the fix then?

**Comment by jagrosh** [comment]
If you take a look at the [docs](http://ci.dv8tion.net/job/JDA/lastCompletedBuild/javadoc/), you'll see the TextChannel extends Channel, which represents a Guild channel. MessageReceivedEvent is for both Guild and Private messages. You need to either use the MessageReceivedEvent#getPrivate() boolean to determine if you need getTextChannel() or getPrivateChannel(), or use the MessageChannel interface returned from MessageReceivedEvent#getChannel()

**Comment by superthread** [comment]
thanks. the bot responds correctly when pinged from the server but not private messages.

**Comment by jagrosh** [comment]
Considering that this was an error in your own code, would you mind closing this issue?

**Comment by jagrosh** [comment]
Also, if you have more questions, this channel will be an excellent resource: https://discord.gg/0SBTUU1wZTUgGuC8
