### ISSUE TITLE
NullPointerException with PRESENCE_UPDATE

### ISSUE THREAD

**Issue by Slimig** [DV8FromTheWorld/JDA#1159]
### Bug Report
My Bot cant load anymore (or it just takes extremeee long)

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behavior
Loading within a few seconds
### Exception or Error
```01:41:28.252 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.internal.requests.WebSocketClient - Got an unexpected error. Please redirect following message to the devs:
			PRESENCE_UPDATE -> {"game":{"emoji":{"name":"💖"},"name":"Custom Status","created_at":1576370481790,"state":"LeT's GeT MiChIeVoUs AnD pOlYaMoRoUs","id":"custom","type":4},"client_status":{"mobile":"online"},"activities":[{"emoji":{"name":"💖"},"name":"Custom Status","created_at":1576370481790,"id":"custom","type":4}],"roles":[],"guild_id":"153566829380370432","user":{"id":"525827250206015559","avatar":"2bd8289e212bbaf48ed55fb980cbccf9","username":"Alicasso","discriminator":"9010"},"status":"online"}
		java.lang.NullPointerException: null
			at net.dv8tion.jda.api.events.user.update.UserUpdateOnlineStatusEvent.<init>(UserUpdateOnlineStatusEvent.java:45)
			at net.dv8tion.jda.internal.handle.PresenceUpdateHandler.handleInternally(PresenceUpdateHandler.java:127)
			at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37)
			at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:843)
			at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:739)
			at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:718)
			at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:881)
			at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
			at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
			at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
			at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
			at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
			at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
			at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```
### Code Example or Reproduction Steps
[UserUpdateOnlineStatusEvent](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateOnlineStatusEvent.java#L42-L47)

Also here the PresenceUpdateHandler.java
[PresenceUpdateHandler](https://github.com/DV8FromTheWorld/JDA/blob/77b787b7b0ec7efaca2d15efc8dc6cf98be883bc/src/main/java/net/dv8tion/jda/internal/handle/PresenceUpdateHandler.java#L109)
> It creates a member but never stores it in the guild
   so it returns null when getMember() is called again

**Comment by MinnDevelopment** [comment]
The `PresenceUpdateHandler`  **does** store the member in the guild. The only situation where `createMember()` does not store it is when guild subscriptions are disabled. Are you using a client account?

**Comment by Slimig** [comment]
Yes I am. But I never had the Problem before :'/.

**Comment by MCOfficer** [comment]
JDA does not support client accounts since they are against the ToS, so i suggest you

a) close this issue
b) stop doing it, for your account's sake

**Comment by Slimig** [comment]
• We will however continue support for the usage of JDA through the client account type through JDABuilder(AccountType.CLIENT). This does not mean it is encouraged or recommended to create applications such as selfbots or custom clients which are prohibited by the Discord Terms of Service.

**Comment by caneleex** [comment]
> > We will however continue support for     the usage of JDA through the client account type through JDABuilder(AccountType.CLIENT)..

This doesn't mean that client account type will be and is maintained.

**Comment by MinnDevelopment** [comment]
This specific issue shouldn't happen anymore on 4.0.0_75

**Comment by Andre601** [comment]
> > We will however continue support for     the usage of JDA through the client account type through JDABuilder(AccountType.CLIENT)..

Just because JDA still supports client accounts doesn't make it any legal.
It is against ToS and there is no discussion around it. Your account may get banned/terminated if you get reported.
