### ISSUE TITLE
AuditLogPaginationAction action_type is null

### ISSUE THREAD

**Issue by Mrtol** [DV8FromTheWorld/JDA#1239]
net.dv8tion.jda.api.exceptions.ParsingException: Unable to resolve value with key action_type to type int: null
    at net.dv8tion.jda.api.utils.data.DataObject.valueError(DataObject.java:656)
    at net.dv8tion.jda.api.utils.data.DataObject.getInt(DataObject.java:487)
    at net.dv8tion.jda.internal.entities.EntityBuilder.createAuditLogEntry(EntityBuilder.java:1570)
    at net.dv8tion.jda.internal.requests.restaction.pagination.AuditLogPaginationActionImpl.handleSuccess(AuditLogPaginationActionImpl.java:152)
    at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:236)
    at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:199)
    at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:240)
    at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:144)
    at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:127)
    at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:416)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by caneleex** [comment]
The error is not helpful on it's own. What did you try to do? Please add more context. By the way, have you even seen the issue template? I guess not.

**Comment by MinnDevelopment** [comment]
This is a discord bug, shouldn't be a problem though.

**Comment by DV8FromTheWorld** [comment]
There has been no change on this for almost 17 months. As this is likely a discord issue I'm going to close this.
