### ISSUE TITLE
LavaPlayer doesn't work when i build the project (2020 pls note that)

### ISSUE THREAD

**Issue by KFPL** [DV8FromTheWorld/JDA#1259]
i have the latest LavaPlayer and JDA version but it doesn't work.

```
[JDA [0 / 1] AudioConnection Guild: 677075702004187148 Sending Thread] ERROR AudioConnection - There was an error while getting next audio packet
java.lang.UnsupportedOperationException
        at com.sedmelluq.discord.lavaplayer.track.playback.TerminatorAudioFrame.getVolume(TerminatorAudioFrame.java:18)
        at com.sedmelluq.discord.lavaplayer.track.playback.AllocatingAudioFrameBuffer.filterFrame(AllocatingAudioFrameBuffer.java:194)
        at com.sedmelluq.discord.lavaplayer.track.playback.AllocatingAudioFrameBuffer.provide(AllocatingAudioFrameBuffer.java:61)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.provide(LocalAudioTrackExecutor.java:398)
        at com.sedmelluq.discord.lavaplayer.track.BaseAudioTrack.provide(BaseAudioTrack.java:92)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:189)
        at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:175)
        at me.KFPL.music.AudioPlayerSendHandler.canProvide(AudioPlayerSendHandler.java:21)
        at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacketRaw(AudioConnection.java:675)
        at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:665)
        at net.dv8tion.jda.api.audio.factory.DefaultSendSystem.lambda$start$0(DefaultSendSystem.java:69)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by MinnDevelopment** [comment]
Lavaplayer exceptions are not a JDA issue. If you want to report a JDA bug please use the bug issue template instead. To report bugs with lavaplayer open an issue at https://github.com/sedmelluq/lavaplayer/issues/new and please include your code as well.
