### ISSUE TITLE
This error occurred while creating the private channel.

### ISSUE THREAD

**Issue by domos121** [DV8FromTheWorld/JDA#1429]
```
[21:45:50 ERROR]: Got an unexpected error. Please redirect following message to the devs:
	CHANNEL_CREATE -> {"last_message_id":"771101169451663360","recipients":[{"public_flags":0,"id":"293496389772509185","avatar":"bc5690168d7d5330b0a8a605a3634b1d","username":"Domos121","discriminator":"6668"}],"id":"524176514263023616","type":1}
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:850) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:339) ~[?:?]
	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1056) ~[?:?]
	at java.util.jar.JarFile.getEntry0(JarFile.java:577) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:506) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.3.jar:git-Paper-202]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Paper-202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.dv8tion.jda.internal.handle.ChannelCreateHandler.handleInternally(ChannelCreateHandler.java:52) ~[?:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:954) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:841) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:819) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
```

**Comment by RedDaedalus** [comment]
I believe this happens when a Bukkit plugin shuts down while JDA is receiving an event.

**Comment by domos121** [comment]
No bukkit is running and working.

**Comment by MinnDevelopment** [comment]
#1337 This is also not a jda bug but a bukkit issue. Ask on their forums instead.
