### ISSUE TITLE
Reactionbug

### ISSUE THREAD

**Issue by LeBaasti** [DV8FromTheWorld/JDA#1440]
I got this message in the console:
[14:44:39] [JDA MainWS-ReadThread/ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
	MESSAGE_REACTION_REMOVE -> {"emoji":{"name":"👎","id":null},"user_id":"269495458454306817","guild_id":"774965907901644802","message_id":"776079900427681812","channel_id":"775385464546000907"}
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_272]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_272]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_272]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_272]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-265]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_272]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_272]
	at net.dv8tion.jda.internal.handle.MessageReactionHandler.handleInternally(MessageReactionHandler.java:147) ~[?:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:954) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:841) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:819) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]

**Comment by MinnDevelopment** [comment]
#1337

**Comment by DManstrator** [comment]
Should be a Bukkit Issue.
