### ISSUE TITLE
Disallowed intents

### ISSUE THREAD

**Issue by nkgcp** [DV8FromTheWorld/JDA#1445]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [ ] I have checked for similar issues.
- [ ] I have updated to the [latest JDA version][download]
- [ ] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
**My code:**
```java
try {
   JDA = JDABuilder.createDefault(loadToken())
            .enableIntents(GatewayIntent.GUILD_MESSAGES, GatewayIntent.DIRECT_MESSAGES, GatewayIntent.GUILD_MEMBERS)
            .addEventListeners(listener = new Listener())
            .setMemberCachePolicy(MemberCachePolicy.ALL)
            .setActivity(Activity.playing("테스트"))
            .build()
            .awaitReady();                         --- line 37
} catch (Exception e) {
     App.getLogger().error("Exception occurred while loading JDA", e);
     System.exit(-1);
}
```
Error Log:
```
...
2020-11-13 10:26:42 [INFO ] [WebSocketClient.java]onConnected(391) : Connected to WebSocket
2020-11-13 10:26:42 [DEBUG] [WebSocketClient.java]onConnected(394) : Connected with gateway intents: 11011011001111
2020-11-13 10:26:42 [DEBUG] [WebSocketClient.java]sendIdentify(688) : Sending Identify-packet...
2020-11-13 10:26:42 [DEBUG] [WebSocketClient.java]onEvent(862) : Got HELLO packet (OP 10). Initializing keep-alive.
2020-11-13 10:26:42 [DEBUG] [WebSocketClient.java]handleDisconnect(455) : WebSocket connection closed with code CloseCode(4014 / Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES or GUILD_MEMBERS.)
2020-11-13 10:26:42 [ERROR] [WebSocketClient.java]handleDisconnect(487) : WebSocket connection was closed and cannot be recovered due to identification issues
CloseCode(4014 / Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES or GUILD_MEMBERS.)
2020-11-13 10:26:42 [DEBUG] [BotRateLimiter.java]lambda$cleanup$3(157) : Removed 2 expired buckets
2020-11-13 10:26:42 [ERROR] [App.java]main(39) : Exception occurred while loading JDA
java.lang.IllegalStateException: Was shutdown trying to await status
	at net.dv8tion.jda.internal.JDAImpl.awaitStatus(JDAImpl.java:464)
	at net.dv8tion.jda.api.JDA.awaitStatus(JDA.java:310)
	at net.dv8tion.jda.api.JDA.awaitReady(JDA.java:360)
	at com.github.nkgcp.discordbot.App.main(App.java:37)
```
Please help me.

**Comment by nkgcp** [comment]
I found solution in troubleshooting page.
