### ISSUE TITLE
Permission Error VIEW_CHANNEL

### ISSUE THREAD

**Issue by nkgcp** [DV8FromTheWorld/JDA#1457]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [ ] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question
This is my code:
``` kotlin
mainChannel = guild.createTextChannel("~~~~")
        .addPermissionOverride(guild.publicRole, null, EnumSet.of(Permission.VIEW_CHANNEL))
        .complete()

for (player in players) {
    mainChannel.manager.putPermissionOverride(player, EnumSet.of(Permission.VIEW_CHANNEL), null)
}
```
and stack trace:
```
Exception in thread "Thread-8" net.dv8tion.jda.api.exceptions.MissingAccessException: Cannot perform action due to a lack of Permission. Missing permission: VIEW_CHANNEL
	at net.dv8tion.jda.internal.managers.ChannelManagerImpl.checkPermissions(ChannelManagerImpl.java:384)
	at net.dv8tion.jda.internal.managers.ChannelManagerImpl.<init>(ChannelManagerImpl.java:71)
	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.lambda$getManager$0(AbstractChannelImpl.java:173)
	at net.dv8tion.jda.api.utils.MiscUtil.locked(MiscUtil.java:127)
	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.getManager(AbstractChannelImpl.java:170)
	at com.github.nkgcp.mafiabot.games.Classic.createTextChannel(Classic.kt:103)
	at com.github.nkgcp.mafiabot.games.Classic.run(Classic.kt:23)
	at com.github.nkgcp.mafiabot.CommandProcesser$start$1.run(CommandProcesser.kt:50)
	at java.lang.Thread.run(Thread.java:748)
```
The same permission error occurs when deleting the 'mainChannel' in above code.
What's wrong with my code?

**Comment by RedstonecraftHD** [comment]
Read the Error! The Bot requires to have the VIEW_CHANNEL Permission on the Discord Server.

**Comment by nkgcp** [comment]
I already gave. Is it wrong to give VIEW_CHANNEL permission by OAuth2?
![스크린샷(6)](https://user-images.githubusercontent.com/65478530/99899151-67c70e00-2cea-11eb-94d1-5dc1ecc3e8c9.png)
](url)

**Comment by DManstrator** [comment]
You can't configure actual permissions in the developer application settings, also not with the invite link since user can easily uncheck all permissions you preset before adding the bot to the guild. So the bot could end up having no permission when joining the server.

In your case, you revoke the read permission for your bot by yourself by denying read permission for everyone. So nobody except people with Administrator permission can see the channel. Make sure to add an override for yourself too.

And you should always check with `Member#hasPermission(GuildChannel, Permission...)` if you actually have a permission in a specific channel.

And for good measure, you should use queue with a success consumer instead of using complete since it will block your bot from doing anything in the meantime. Read more about in the [RestAction wiki entry](https://github.com/DV8FromTheWorld/JDA/wiki/7%29-Using-RestAction#using-queue),

**Comment by nkgcp** [comment]
Thanks. I just solved my problem.
