### ISSUE TITLE
MessageAction.addFile(file);

### ISSUE THREAD

**Issue by DomiWe** [DV8FromTheWorld/JDA#1600]
I am adding am Embed Message with a valid attachment. Why i get the following Expcetion ?
The file is existing.

java.lang.IllegalArgumentException: Provided file either does not exist or cannot be read from!
	at net.dv8tion.jda.internal.utils.Checks.check(Checks.java:43)
	at net.dv8tion.jda.internal.requests.restaction.MessageActionImpl.addFile(MessageActionImpl.java:337)
	at net.dv8tion.jda.internal.requests.restaction.MessageActionImpl.addFile(MessageActionImpl.java:51)
	at net.dv8tion.jda.api.requests.restaction.MessageAction.addFile(MessageAction.java:609)
	at discord.DiscordBot.onMessageReceived(DiscordBot.java:126)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:435)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:956)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:994)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by DV8FromTheWorld** [comment]
> Provided file either does not exist or cannot be read from
