### ISSUE TITLE
[15:39:01] [JDA MainWS-ReadThread/ERROR] [jdalib.jda.api.JDA]: One of the EventListeners had an uncaught exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by aut1sto** [DV8FromTheWorld/JDA#1608]
Сonsole randomly spams this error

[15:39:01] [JDA MainWS-ReadThread/ERROR] [jdalib.jda.api.JDA]: One of the EventListeners had an uncaught exception
java.lang.NullPointerException: null
        at br.net.fabiozumbi12.UltimateChat.Sponge.discord.UCDiscord.onMessageReceived(UCDiscord.java:255) ~[UCDiscord.class:?]
        at jdalib.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:426) ~[ListenerAdapter.class:?]
        at jdalib.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) [InterfacedEventManager.class:?]
        at jdalib.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:64) [EventManagerProxy.class:?]
        at jdalib.jda.internal.JDAImpl.handleEvent(JDAImpl.java:165) [JDAImpl.class:?]
        at jdalib.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122) [MessageCreateHandler.class:?]
        at jdalib.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) [SocketHandler.class:?]
        at jdalib.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:877) [WebSocketClient.class:?]
        at jdalib.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:765) [WebSocketClient.class:?]
        at jdalib.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:744) [WebSocketClient.class:?]
        at jdalib.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:915) [WebSocketClient.class:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) [ListenerManager.class:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) [ReadingThread.class:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) [ReadingThread.class:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) [ReadingThread.class:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [ReadingThread.class:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [ReadingThread.class:?]

**Comment by MinnDevelopment** [comment]
That is an error in your own code. Also #1337
