### ISSUE TITLE
User.getName() or User.getAsTag() doesn't work on some users and gives an exception.

### ISSUE THREAD

**Issue by vlOd2** [DV8FromTheWorld/JDA#1619]
Hello!

I have recently started using JDA and noticed an issue while I was trying to make a cmd.

So there is this cmd where you ping someone and it gets the id of the pinged user.
Here is the code I am using for that, and yes I know it's not the most efficient but it works.

`String PingedUserID = Arguments[1].replace("<", "").replace("@", "").replace("!", "").replace(">", "");
User PingedUser = Cmd.DiscordBot.getUserById(PingedUserID);`

While this gets the id succesfully and yes there is something to check if an actual ping was typed something else happens for some specific users.

It's consistent for some specific users when I am trying to use .getName() and .getAsTag().
It trows: java.lang.reflect.InvocationTargetException

Here is the full exception:

> 
[JDA MainWS-ReadThread] ERROR JDA - Couldn't access annotated EventListener method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.dv8tion.jda.api.hooks.AnnotatedEventManager.lambda$handle$0(AnnotatedEventManager.java:95)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at net.dv8tion.jda.api.hooks.AnnotatedEventManager.lambda$handle$1(AnnotatedEventManager.java:90)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at net.dv8tion.jda.api.hooks.AnnotatedEventManager.handle(AnnotatedEventManager.java:90)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:956)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:994)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.NullPointerException
	at me.vlOd.PintoUtilities.Commands.EndCommand.onMessageReceived(EndCommand.java:70)
	... 25 more
>

**Comment by Andre601** [comment]
1. Follow the issue template please.
2. If you use getUserById from JDA itself is there a chance that the returned user is null.
3. Use Message#getMentionedUsers if you can access the message send by the user. You can then use get(0) on that. Note that the returned list can be empty.

**Comment by MinnDevelopment** [comment]
Use `getMentionedUsers` instead.

Closing #1337
