### ISSUE TITLE
The Console sad i should report this xD

### ISSUE THREAD

**Issue by Bastitron** [DV8FromTheWorld/JDA#1651]
INTERACTION_CREATE -> {"data":{"component_type":2,"custom_id":"BUTTON_RESTART"},"id":"851150279247396866","type":3,"message":{"mention_everyone":false,"pinned":false,"components":[{"components":[{"custom_id":"BUTTON_SHUTDOWN","style":4,"label":"Herunterfahren","type":2,"hash":"fT1WQEgs"},{"custom_id":"BUTTON_RESTART","style":2,"label":"Neustarten","type":2,"hash":"DHujkM2D"}],"type":1}],"attachments":[],"author":{"bot":true,"public_flags":0,"id":"813465025540128818","avatar":"fa0c18523a4bffdc3ac3f67b02d597a3","username":"AngelTaiga","discriminator":"4358"},"flags":0,"type":0,"mention_roles":[],"edited_timestamp":null,"content":"","tts":false,"mentions":[],"id":"851150272872185886","embeds":[{"type":"rich","title":"**AngelTaiga**"}],"channel_id":"813511396611588136","timestamp":"2021-06-06T17:27:18.660000+00:00"},"version":1,"user":{"public_flags":128,"id":"511151322242744331","avatar":"3b8da153a02e916f4ef6e73ebe189e19","username":"Bastitron","discriminator":"1733"},"channel_id":"813511396611588136","application_id":"813465025540128818","token
	(TOKEN)
	java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5732a3f5 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@de6b8bd[Shutting down, pool size = 1, active threads = 0, queued tasks = 1, completed tasks = 13]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at net.dv8tion.jda.internal.interactions.InteractionHookImpl.<init>(InteractionHookImpl.java:64)
	at net.dv8tion.jda.internal.interactions.InteractionImpl.<init>(InteractionImpl.java:50)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:61)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[JDA MainWS-WriteThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] ERROR WebSocketClient - Encountered IDENTIFY Rate Limit!
[JDA MainWS-ReadThread] WARN WebSocketClient - Got disconnected from WebSocket (Code 1000). Appending to reconnect queue
[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO JDA - Finished Loading!

**Comment by MinnDevelopment** [comment]
Closing since you didn't provide the required information from the bug report template. #1337 

You likely just shutdown stuff while it tried to schedule a timeout.
