### ISSUE TITLE
JSONException when retrieving history with Webhooks Messages

### ISSUE THREAD

**Issue by MinusKube** [DV8FromTheWorld/JDA#168]
When I retrieve an history with a Webhook Message inside it, JDA throws a JSONException because the object "url" is not found.

```
org.json.JSONException: JSONObject["url"] not found.
        at org.json.JSONObject.get(JSONObject.java:477)
        at org.json.JSONObject.getString(JSONObject.java:723)
        at net.dv8tion.jda.handle.EntityBuilder.createMessageEmbed(EntityBuilder.java:591)
        at net.dv8tion.jda.handle.EntityBuilder.createMessage(EntityBuilder.java:508)
        at net.dv8tion.jda.MessageHistory.retrieve(MessageHistory.java:113)
        at net.dv8tion.jda.MessageHistory.retrieve(MessageHistory.java:80)```

I've tried with JDA 2.2.1_353 and JDA 2.3.0_379, the error occurs on both.

**Comment by MinnDevelopment** [comment]
This is fixed in 3.x Beta. Please consider switching over unless you need audio support.
