### ISSUE TITLE
NoSuchMethodError: 'org.slf4j.spi.SLF4JServiceProvider org.slf4j.LoggerFactory.getProvider()'

### ISSUE THREAD

**Issue by otomir23** [DV8FromTheWorld/JDA#1737]
## General Troubleshooting
  
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked for similar issues.
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

I am using JDA bot as a Paper Minecraft plugin, and it crashes on startup with exception. I tried using Logger Implementation, copying files from SLD4J jar file and patching server JAR, but none of this worked. I have no idea how to fix it.

I am packaging JAR with Shade plugin.

### Exception or Error
```
[12:36:27] [Server thread/ERROR]: Error occurred while enabling DiscordIntegration v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'org.slf4j.spi.SLF4JServiceProvider org.slf4j.LoggerFactory.getProvider()'
	at org.slf4j.MDC.<clinit>(MDC.java:89) ~[patched_1.17.jar:git-Airplane-13]
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:295) ~[?:?]
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:268) ~[?:?]
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1870) ~[?:?]
	at otomir23.discordintegration.DiscordIntegration.onEnable(DiscordIntegration.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Airplane-13]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Airplane-13]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Airplane-13]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Airplane-13]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Airplane-13]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:714) ~[patched_1.17.jar:git-Airplane-13]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:307) ~[patched_1.17.jar:git-Airplane-13]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1189) ~[patched_1.17.jar:git-Airplane-13]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.jar:git-Airplane-13]
	at java.lang.Thread.run(Thread.java:831) [?:?]


```

**Comment by MinnDevelopment** [comment]
You have an incompatible SLF4J implementation. JDA uses slf4j-api 1.7 by default, if that is not compatible with your implementation you need to either change the version of this implementation or the referenced API version to match. This is not a JDA bug, and you haven't provided enough information to pin down the exact issue in your setup.
