### ISSUE TITLE
bot dont send a msg

### ISSUE THREAD

**Issue by 6test55566** [DV8FromTheWorld/JDA#1780]
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/hcmUZxBS

Hey! i wes trying to make my bot send a msg, and this error spam my i got 2 errors 

error num 1 spamd the consle:
```
16.08 15:42:55 [Server] ERROR [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
16.08 15:42:55 [Server] INFO MESSAGE_DELETE -> {"guild_id":"742674027025268796","id":"876913930981756928","channel_id":"818383354462076933"}
16.08 15:42:55 [Server] INFO java.lang.IllegalStateException: zip file closed
16.08 15:42:55 [Server] INFO at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
16.08 15:42:55 [Server] INFO at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
16.08 15:42:55 [Server] INFO at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
16.08 15:42:55 [Server] INFO at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
16.08 15:42:55 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:42:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
16.08 15:42:55 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:42:55 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:42:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
16.08 15:42:55 [Server] INFO at net.dv8tion.jda.internal.handle.MessageDeleteHandler.handleInternally(MessageDeleteHandler.java:61) ~[?:?]
16.08 15:42:55 [Server] INFO at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
16.08 15:42:55 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[?:?]
16.08 15:42:55 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[?:?]
16.08 15:42:55 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[?:?]
16.08 15:42:55 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[?:?]
16.08 15:42:55 [Server] INFO at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
16.08 15:42:55 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
16.08 15:42:55 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
16.08 15:42:55 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
16.08 15:42:55 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
16.08 15:42:55 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
16.08 15:42:55 [Server] INFO at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
```
----------------------------------------------------------------------------------------------------------------------

**error num 2:**
```16.08 15:48:14 [Server] INFO [net.dv8tion.jda.api.JDA] Login Successful!
16.08 15:48:14 [Server] ERROR null
16.08 15:48:14 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'test' in plugin inbar-server v2.0
16.08 15:48:14 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
16.08 15:48:14 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.TextChannel.sendMessage(java.lang.CharSequence)" because "channel" is null
16.08 15:48:14 [Server] INFO at net.inbar.main.commands.testcmd.onCommand(testcmd.java:47) ~[?:?]
16.08 15:48:14 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-786]
16.08 15:48:14 [Server] INFO ... 19 more
16.08 15:48:14 [Server] INFO [net.dv8tion.jda.internal.requests.WebSocketClient] Connected to WebSocket
16.08 15:48:14 [Server] INFO [net.dv8tion.jda.api.JDA] Finished Loading!
```
----------------------------------------------------------------------------------------------------------------------
and this is my code:
```java
            JDA jda = null;
            try {
                jda = JDABuilder.createDefault("token lol").build();
            } catch (LoginException e) {
                e.printStackTrace();
            }

            assert jda != null;
            TextChannel channel = jda.getTextChannelById("818383354462076933");
            assert channel != null;
            channel.sendMessage("test!" + "test2");

```
if forgot to menstion stuff tell me

**Comment by freya022** [comment]
This issue is a Bukkit issue, not JDA, you are likely using JDA after your plugin has been unloaded, please refer to [this issue](https://github.com/DV8FromTheWorld/JDA/issues/1761#issuecomment-892921634)

**Comment by Andre601** [comment]
- Duplicate of #1429 
- Follow the issue templates please!

**Comment by 6test55566** [comment]
oh ok i will try fix it
