### ISSUE TITLE
Please redirect the following to devs

### ISSUE THREAD

**Issue by LauraRussels** [DV8FromTheWorld/JDA#1861]
[10.10 22:31:58] [Server] [ERROR] [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect the following message to the devs:
[10.10 22:31:58] [Server] 	JDA 4.3.0_334
[10.10 22:31:58] [Server] 	MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"components":[],"attachments":[],"author":{"public_flags":256,"id":"206504892091727872","avatar":"b7ed5bd754986a3bb8429815750c9e18","username":"laurarussels","discriminator":"3188"},"flags":0,"type":0,"mention_roles":[],"nonce":"896857611796742144","edited_timestamp":null,"content":"!verify","tts":false,"referenced_message":null,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2021-09-29T12:19:15.281298+00:00","roles":["892747928341454898","799370060871368756","748868726526574613"],"pending":false,"hoisted_role":"892747928341454898","deaf":false,"mute":false,"avatar":null,"is_pending":false},"guild_id":"748855129578536982","id":"896857614380576850","embeds":[],"channel_id":"896735800543285339","timestamp":"2021-10-10T20:31:58.077000+00:00"}
[10.10 22:31:58] [Server] java.lang.IllegalStateExceptionzip file closed
[10.10 22:31:58] [Server] 	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:912) ~[?:?]
[10.10 22:31:58] [Server] 	at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
[10.10 22:31:58] [Server] 	at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1118) ~[?:?]
[10.10 22:31:58] [Server] 	at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
[10.10 22:31:58] [Server] 	at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
[10.10 22:31:58] [Server] 	at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
[10.10 22:31:58] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Paper-788]
[10.10 22:31:58] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
[10.10 22:31:58] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-788]
[10.10 22:31:58] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-788]
[10.10 22:31:58] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
[10.10 22:31:58] [Server] 	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:40) ~[?:?]
[10.10 22:31:58] [Server] 	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
[10.10 22:31:58] [Server] 	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[?:?]
[10.10 22:31:58] [Server] 	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[?:?]
[10.10 22:31:58] [Server] 	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[?:?]
[10.10 22:31:58] [Server] 	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991) ~[?:?]
[10.10 22:31:58] [Server] 	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
[10.10 22:31:58] [Server] 	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
[10.10 22:31:58] [Server] 	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
[10.10 22:31:58] [Server] 	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
[10.10 22:31:58] [Server] 	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
[10.10 22:31:58] [Server] 	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
[10.10 22:31:58] [Server] 	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]

**Comment by MinnDevelopment** [comment]
Duplicate of #1429 #1440 #1761 #1771 #1780

This is an issue with bukkit not jda.

**Comment by LauraRussels** [comment]
Recognised & fixed
