### ISSUE TITLE
NullPointerException for WebSocketClient while GUILD_ROLE_UPDATE

### ISSUE THREAD

**Issue by gamerjungexd** [DV8FromTheWorld/JDA#1904]
Hey,

I created the error due to assigning the bot the administration role which he didnt had until then.
Here the stacktrace. Just wrote this, because there was the request to forward it to the devs:

[ERROR | JDA MainWS-ReadThread] 2021-11-25 00:10:33,237 net.dv8tion.jda.internal.requests.WebSocketClient - Got an unexpected error. Please redirect the following message to the devs:
	JDA 4.3.0_348
	GUILD_ROLE_UPDATE -> {"role":{"color":0,"unicode_emoji":null,"permissions":"272100440","managed":true,"name":"Secretary","icon":null,"mentionable":false,"position":4,"id":"911591572452302870","hoist":false,"tags":{"bot_id":"764947804236939305"}},"guild_id":"570406198927425537","guild_hashes":{"metadata":{"hash":"IaJr4a5XZe8"},"channels":{"hash":"wvf3V2gcmvM"},"roles":{"hash":"wrDKmP2esrc"},"version":1}}
java.lang.NullPointerException
	at net.dv8tion.jda.internal.handle.GuildRoleUpdateHandler.handleInternally(GuildRoleUpdateHandler.java:129)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
	
	
Feel free to contact me if you need more informations. Hopes this helps you.

**Comment by Xirado** [comment]
#1903 fixes this
