### ISSUE TITLE
I'm using jda to build an android bot app 

### ISSUE THREAD

**Issue by SHUbham23-rgb** [DV8FromTheWorld/JDA#1914]
Process: com.example.jdabot, PID: 18944
    java.lang.ExceptionInInitializerError
        at net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:68)
        at net.dv8tion.jda.api.requests.GatewayIntent.getRaw(GatewayIntent.java:255)
        at net.dv8tion.jda.api.requests.GatewayIntent.<clinit>(GatewayIntent.java:169)
        at net.dv8tion.jda.api.JDABuilder.<clinit>(JDABuilder.java:58)
        at net.dv8tion.jda.api.JDABuilder.createLight(JDABuilder.java:241)
        at com.example.jdabot.MainActivity.<init>(MainActivity.java:21)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1251)

here is my code

 JDA jda;

    {
        try {
            jda = JDABuilder.createLight(token).build();
        } catch (LoginException e) {
            e.printStackTrace();
        }
    }

**Comment by freya022** [comment]
I can confirm it works for Android, even if it's a niche use case

Not a reason to open an issue tho, since you don't have any

**Comment by MinnDevelopment** [comment]
We don't officially support android (for various reasons), but I'll just move this to a discussion.
