### ISSUE TITLE
Error when creating new guild role

### ISSUE THREAD

**Issue by Korlimann** [DV8FromTheWorld/JDA#1969]
When adding a new role to the server, this error occured. It said to forward this to the devs, so I hope this is the right place

```
[JDA MainWS-ReadThread] ERROR WebSocketClient - Got an unexpected error. Please redirect the following message to the devs:
	JDA 4.3.0_348
	GUILD_ROLE_UPDATE -> {"role":{"color":0,"unicode_emoji":null,"permissions":"8","managed":true,"name":"PotBot","icon":null,"mentionable":false,"position":2,"id":"923608305992097883","hoist":false,"tags":{"bot_id":"703961094468665354"}},"guild_id":"703962182282641418","guild_hashes":{"metadata":{"hash":"Kj95HmHocyk"},"channels":{"hash":"loxiasV/CbU"},"roles":{"hash":"LbPS+ZbhKP4"},"version":1}}
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.RoleIcon.getIconId()" because "oldIcon" is null
	at net.dv8tion.jda.internal.handle.GuildRoleUpdateHandler.handleInternally(GuildRoleUpdateHandler.java:129)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[JDA MainWS-ReadThread] ERROR WebSocketClient - Got an unexpected error. Please redirect the following message to the devs:
	JDA 4.3.0_348
	GUILD_ROLE_UPDATE -> {"role":{"color":3066993,"unicode_emoji":null,"permissions":"6442450952","managed":true,"name":"PotBot-Test","icon":null,"mentionable":false,"position":3,"id":"732330589327327313","hoist":false,"tags":{"bot_id":"732328151652368414"}},"guild_id":"703962182282641418","guild_hashes":{"metadata":{"hash":"Kj95HmHocyk"},"channels":{"hash":"loxiasV/CbU"},"roles":{"hash":"LbPS+ZbhKP4"},"version":1}}
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.RoleIcon.getIconId()" because "oldIcon" is null
	at net.dv8tion.jda.internal.handle.GuildRoleUpdateHandler.handleInternally(GuildRoleUpdateHandler.java:129)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[JDA MainWS-ReadThread] ERROR WebSocketClient - Got an unexpected error. Please redirect the following message to the devs:
	JDA 4.3.0_348
	GUILD_ROLE_UPDATE -> {"role":{"color":3447003,"unicode_emoji":null,"permissions":"6546771529","managed":false,"name":"Admin","icon":null,"mentionable":false,"position":4,"id":"706563614395596892","hoist":false},"guild_id":"703962182282641418","guild_hashes":{"metadata":{"hash":"Kj95HmHocyk"},"channels":{"hash":"loxiasV/CbU"},"roles":{"hash":"LbPS+ZbhKP4"},"version":1}}
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.RoleIcon.getIconId()" because "oldIcon" is null
	at net.dv8tion.jda.internal.handle.GuildRoleUpdateHandler.handleInternally(GuildRoleUpdateHandler.java:129)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[JDA MainWS-ReadThread] ERROR WebSocketClient - Got an unexpected error. Please redirect the following message to the devs:
	JDA 4.3.0_348
	GUILD_ROLE_UPDATE -> {"role":{"color":3447003,"unicode_emoji":null,"permissions":"1071698660929","managed":false,"name":"Test Role 1","icon":null,"mentionable":false,"position":1,"id":"923608624528511008","hoist":false},"guild_id":"703962182282641418","guild_hashes":{"metadata":{"hash":"Kj95HmHocyk"},"channels":{"hash":"loxiasV/CbU"},"roles":{"hash":"1Ex7OIY07M8"},"version":1}}
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.RoleIcon.getIconId()" because "oldIcon" is null
	at net.dv8tion.jda.internal.handle.GuildRoleUpdateHandler.handleInternally(GuildRoleUpdateHandler.java:129)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

```

**Comment by duncte123** [comment]
Update JDA, the latest version is `4.4.0_352`
