### ISSUE TITLE
java.lang.NoSuchMethodError: org.tritonus.share.sampled.AudioUtils.millis2Frames(JF)J

### ISSUE THREAD

**Issue by nicksellis102** [DV8FromTheWorld/JDA#20]
I tried using your audio example and it gave this error.

`java.lang.NoSuchMethodError: org.tritonus.share.sampled.AudioUtils.millis2Frames(JF)J
	at org.tritonus.sampled.convert.SampleRateConversionProvider$SampleRateConverterStream.resizeBuffers(SampleRateConversionProvider.java:292)
	at org.tritonus.sampled.convert.SampleRateConversionProvider$SampleRateConverterStream.<init>(SampleRateConversionProvider.java:276)
	at org.tritonus.sampled.convert.SampleRateConversionProvider.getAudioInputStream(SampleRateConversionProvider.java:111)
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at net.dv8tion.jda.audio.player.Player.setAudioSource(Player.java:79)
	at net.dv8tion.jda.audio.player.FilePlayer.setAudioFile(FilePlayer.java:46)
	at net.dv8tion.jda.audio.player.FilePlayer.<init>(FilePlayer.java:34)
	at com.CreepersHelp.jda.AudioExample.onGuildMessageReceived(AudioExample.java:101)
	at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:140)
	at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:54)
	at net.dv8tion.jda.handle.MessageReceivedHandler.handle(MessageReceivedHandler.java:45)
	at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:141)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)`

**Comment by DV8FromTheWorld** [comment]
I didn't encounter this error when developing with intellij, however many people have reported this error in the last 24 hours.
A fix will be out soon

**Comment by DV8FromTheWorld** [comment]
This should now be fixed as of build 115, so I am closing this. IF you still encounter the problem feel free to reopen the issue.
