### ISSUE TITLE
NewsChannel#sendMessage() will cause double transmission

### ISSUE THREAD

**Issue by yuchan2215** [DV8FromTheWorld/JDA#2019]
I use deepL because I do not live in an English speaking country!

## General Troubleshooting
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behavior

Running such a code may cause the message to be sent twice
```Kotlin
jda.getNewsChannelById("Channel Id")?.sendMessage(message)?.queue()
```

Common to all
 - Oracle Java 17.0.2
 - JDA v5.0.0-alpha.5

It turns out that the event occurs under the following conditions
 - Running on the following environment
   - Ubuntu20.04 on Green KVM(Ryzen KVM VPS RAM 8G)
   - News channel with 1,500 people authorized to view it.

I was unable to reproduce the problem in the following environment

 - Running on the following environment
   - Windows11 in My Home (RAM 32G)
   - News channel with 9 people authorized to view it.
 - Running on the following environment
   - Windows11 in My Home (RAM 32G)
   - News channel with 1,500 people authorized to view it.
 - Running on the following environment
   - Ubuntu20.04 on Green KVM(Ryzen KVM VPS RAM 8G)
   - News channel with 9 people authorized to view it.

### Code Example or Reproduction Steps

```Kotlin
jda.getNewsChannelById("Channel Id")?.sendMessage(message)?.queue()
```

### Code for JDABuilder or DefaultShardManagerBuilder Used

```Kotlin
JDABuilder
.createDefault(EnvWrapper.DISCORD_TOKEN)
.setMemberCachePolicy(MemberCachePolicy.ALL)
.enableIntents(GatewayIntent.GUILD_MEMBERS)
.setChunkingFilter(ChunkingFilter.ALL)
.build()
```

### Exception or Error

Errors don't seem to occur every time there is a double transmission.
FullCode: https://github.com/YululiServer/YobSubCord/tree/3b465fb627cafc672ae8ca6a8fb6bb812bf8e49a
```
2022/02/07 05:14:44 ERROR [JDA RateLimit-Worker 4] - There was an I/O error while executing a REST request: timeout
2022/02/07 05:14:44 ERROR [ForkJoinPool.commonPool-worker-2] - RestAction queue returned failure: [ErrorResponseException] -1: java.net.SocketTimeoutException
java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:201)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:252)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:141)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:124)
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.dv8tion.jda.api.exceptions.ContextException: null
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539)
        at net.dv8tion.jda.api.requests.RestAction$queue.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
        at Script1.run(Script1.groovy:1)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
        at xyz.miyayu.yobsub.yobsubcord.discord.commands.Eval.eval(Eval.kt:54)
        at xyz.miyayu.yobsub.yobsubcord.discord.commands.Eval.onMessageReceived(Eval.kt:25)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:359)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:165)
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:111)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by yuchan2215** [comment]
In the official Discord, it was pointed out that it might be a problem with our network. However, since the symptoms fluctuate depending on the number of people, I have created this!

**Comment by MinnDevelopment** [comment]
This is an issue when the request is successfully handled on discord's end, but the response times out due to your connection, which results in a retry by JDA. You can disable request timeout retries with [JDABuilder#setRequestTimeoutRetry(false)](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDABuilder.html#setRequestTimeoutRetry(boolean)).
