### ISSUE TITLE
Alpha.7 sending embed/message to TextChannel

### ISSUE THREAD

**Issue by portlek** [DV8FromTheWorld/JDA#2040]
## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report
When you send a message/embed to a text channel it occurs.

### Expected Behavior
the message should be send successfully.

### Code Example or Reproduction Steps
textChannel.sendMessage('').queue(); that's it.

### Code for JDABuilder or DefaultShardManagerBuilder Used
a simple jda builder, nothing different from old version i used.

### Exception or Error
```
[JDA RateLimit-Worker 2] ERROR net.dv8tion.jda.internal.requests.Requester - There was an unexpected error while executing a REST request
java.lang.ClassCastException: class net.dv8tion.jda.internal.entities.TextChannelImpl cannot be cast to class net.dv8tion.jda.internal.entities.PrivateChannelImpl (net.
dv8tion.jda.internal.entities.TextChannelImpl and net.dv8tion.jda.internal.entities.PrivateChannelImpl are in unnamed module of loader 'app')
        at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:1369)
        at net.dv8tion.jda.internal.requests.restaction.MessageActionImpl.handleSuccess(MessageActionImpl.java:616)
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:268)
        at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:237)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:141)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:124)
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
https://github.com/DV8FromTheWorld/JDA/commit/ac3104d3b0706e3f48c2da1c7094642174b72880 this change made this bug.

**Comment by portlek** [comment]
probably #2039 will fix this issue.
