### ISSUE TITLE
I can't do this

### ISSUE THREAD

**Issue by gts1108** [DV8FromTheWorld/JDA#2050]
## Bug Report

I have this bug but i tried to know what is wrong with it but i don't understand

```

public class BotStartup {
	public static void main(String [] args) throws LoginException {
		JDABuilder jda = JDABuilder.createDefault("--snip--");
		jda.setActivity(Activity.playing("!test"));
		jda.setStatus(OnlineStatus.ONLINE);
		jda.build();
	}
}
```

##ERROR

```
Exception in thread "main" java.lang.NoClassDefFoundError: net/dv8tion/jda/api/JDABuilder
	at Main.BotStartup.main(BotStartup.java:11)
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.api.JDABuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 1 more
```

**Comment by DV8FromTheWorld** [comment]
@gts1108 Please regenerate your bot token. Posting your bot token allows anyone to log in as your bot.

**Comment by MinnDevelopment** [comment]
Check the [troubleshooting page](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#noclassdeffounderror-or-classnotfoundexception-on-startup)

We have recommended setup guides available in our wiki: https://github.com/DV8FromTheWorld/JDA/wiki/2%29-Setup

**Comment by gts1108** [comment]
@DV8FromTheWorld  When i post the issue, i change the bot token.
@MinnDevelopment  Thank You for the links.
