### ISSUE TITLE
Misleading timeout errors when calling InteractionHook#editOriginal() instead of IMessageEditCallback#editMessage()

### ISSUE THREAD

**Issue by alexpado** [DV8FromTheWorld/JDA#2114]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

Either: 

- Getting an *immediate* exception (instead of ~4s) saying that you can't use `InteractionHook#editOriginal()` without calling `IMessageEditCallback#deferEdit()` beforehand
- Having `InteractionHook#editOriginal` acting the same way as `IMessageEditCallback#editMessage()` when `IMessageEditCallback#deferEdit()` wasn't called beforehand
- Changing the exception message to avoid any reaction like "Oh my bot didn't go fast enough, too bad"

### Code Example for Reproduction Steps

```java
// This won't work
@Override
public void onButtonInteraction(@NotNull ButtonInteractionEvent event) {
    if (event.getComponentId().equals("oof")) {
        event.getHook().editOriginal("Edited !").complete();
    }
}

// This will work
@Override
public void onButtonInteraction(@NotNull ButtonInteractionEvent event) {
    if (event.getComponentId().equals("oof")) {
        event.editMessage("Edited !").complete();
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder builder = JDABuilder.createLight(TOKEN);
builder.addEventListeners(this);
builder.build();
```

### Exception or Error

```yesyes
# Using .queue()

WARN InteractionHook - Up to 1 Interaction Followup Messages Timed out! Did you forget to acknowledge the interaction?

# Using .complete()

WARN InteractionHook - Up to 1 Interaction Followup Messages Timed out! Did you forget to acknowledge the interaction?
ERROR JDA - One of the EventListeners had an uncaught exception

java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Timed out waiting for interaction acknowledgement
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:220)
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:633)
	at fr.alexpado.playground.JDAPlayground.onButtonInteraction(JDAPlayground.java:64)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:361)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:164)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:131)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:83)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:957)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:844)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:822)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:996)
```

**Comment by MinnDevelopment** [comment]
This is working as intended. Please read the documentation for [Interaction](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/interactions/Interaction.html). You *must* acknowledge the interaction before using the hook. Hook messages will be put into a queue until the ack is sent, if that never happens they time out like this.
