### ISSUE TITLE
 Unsupported flags: 256

### ISSUE THREAD

**Issue by dmkenza** [DV8FromTheWorld/JDA#2145]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

JDA shoud run on Android.

Seems like 
Line  Pattern.compile("[\\w-]+", Pattern.UNICODE_CHARACTER_CLASS);

 in class  net.dv8tion.jda.internal.utils.Checks 
 
 leads to error. 

### Code Example for Reproduction Steps

```java
JDABuilder.createDefault(TOKEN)
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder.createDefault(TOKEN)
```

### Exception or Error

```yesyes
java.lang.ExceptionInInitializerError
        at net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:75)
        at net.dv8tion.jda.api.requests.GatewayIntent.getRaw(GatewayIntent.java:255)
        at net.dv8tion.jda.api.requests.GatewayIntent.<clinit>(GatewayIntent.java:169)
        at net.dv8tion.jda.api.JDABuilder.<clinit>(JDABuilder.java:58)
        at net.dv8tion.jda.api.JDABuilder.createDefault(JDABuilder.java:125)
        at com.kenza.lunabot.LunaBot.startBot(LunaBot.kt:20)
        at com.kenza.lunabot.LunaBot$startBot$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
        at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@588b3fd, Dispatchers.Main.immediate]
    Caused by: java.lang.IllegalArgumentException: Unsupported flags: 256
        at java.util.regex.Pattern.<init>(Pattern.java:1401)
        at java.util.regex.Pattern.compile(Pattern.java:992)
        at net.dv8tion.jda.internal.utils.Checks.<clinit>(Checks.java:34)
        	... 22 more
```

**Comment by MinnDevelopment** [comment]
JDA does not support android.
