### ISSUE TITLE
Random IllegalStateException

### ISSUE THREAD

**Issue by BooleanCube** [DV8FromTheWorld/JDA#2154]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

Cache properly without errors

### Code Example for Reproduction Steps

```java
no code written
the bug is reproduced when it tries to cache channels
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
DefaultShardManagerBuilder lollipop = DefaultShardManagerBuilder.createDefault(Secret.TOKEN)
                .setChunkingFilter(ChunkingFilter.ALL)
                .setMemberCachePolicy(MemberCachePolicy.ALL)
                .enableIntents(GatewayIntent.GUILD_MEMBERS)
                .setActivity(Activity.watching("anime | " + Constant.PREFIX + "help"))
                .setShardsTotal(4)
                .addEventListeners(new Listener());
ShardManager bot = lollipop.build();
```

### Exception or Error

```yesyes
java.lang.IllegalStateException: Guild does not have a self member
	at net.dv8tion.jda.internal.entities.GuildImpl.getSelfMember(GuildImpl.java:545)
	at net.dv8tion.jda.internal.handle.ChannelUpdateHandler.handleInternally(ChannelUpdateHandler.java:388)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.handle.EventCache$CacheNode.execute(EventCache.java:150)
	at net.dv8tion.jda.internal.handle.EventCache.playbackCache(EventCache.java:102)
	at net.dv8tion.jda.internal.entities.EntityBuilder.createVoiceChannel(EntityBuilder.java:1102)
	at net.dv8tion.jda.internal.entities.EntityBuilder.createGuildChannel(EntityBuilder.java:329)
	at net.dv8tion.jda.internal.entities.EntityBuilder.createGuild(EntityBuilder.java:261)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.completeSetup(GuildSetupNode.java:358)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.handleMemberChunk(GuildSetupNode.java:258)
	at net.dv8tion.jda.internal.handle.GuildSetupController.onMemberChunk(GuildSetupController.java:226)
	at net.dv8tion.jda.internal.handle.GuildMembersChunkHandler.handleInternally(GuildMembersChunkHandler.java:63)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by MinnDevelopment** [comment]
This should already be fixed on the latest version of jda, which is 5.0.0-alpha.12. See #2004 #2045
