### ISSUE TITLE
JDA can't send file. [net.dv8tion.jda.internal.requests.RateLimiter]

### ISSUE THREAD

**Issue by Andrei0016** [DV8FromTheWorld/JDA#2168]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

The bot starts and should send a file in a specific channel when the minecraft plugin is turned off aka server is shut down, the file exists and I get no errors in the editor. It gives me the error [net.dv8tion.jda.internal.requests.RateLimiter] but only one file is sent not any more.

### Code Example for Reproduction Steps

```java
public static void saveConfig(List<String> list, File file) throws IOException {
        BufferedWriter output = new BufferedWriter(new FileWriter(file));
        for (String line : list) {
            output.write(line);
            output.newLine();
        }
        output.close();
    }


    @Override
    public void onDisable() {
        messageList.add("[" + new Date(System.currentTimeMillis()) + "] " + "Server Shutdown");
        Date date = new Date(System.currentTimeMillis());
        File LogFile = new File(Bukkit.getServer().getPluginManager().getPlugin("NoCheat").getDataFolder(), date + " log");
        TextChannel textChannel = this.bot.getTextChannelById("991332686641766472");
        try {
            saveConfig(messageList, LogFile);
        } catch (IOException e) {
            e.printStackTrace();
        }
        textChannel.sendFile(LogFile, date + " log").queue();

        if (this.bot != null) {
            this.bot.shutdown();
        }
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
private void loadBot() throws LoginException {
        this.bot = JDABuilder
                .createDefault("TOKEN")
                .setActivity(Activity.competing("COMPETITION"))
                .addEventListeners(new commands(messageList, bot))
                .build();
    }
```

### Exception or Error

```yesyes
[18:25:00 ERROR]: [net.dv8tion.jda.internal.requests.Requester] There was an unexpected error while executing a REST request
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:519) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at okhttp3.internal.http2.Http2Connection.writeSynResetLater$okhttp(Http2Connection.kt:1014) ~[?:?]
        at okhttp3.internal.http2.Http2Stream.closeLater(Http2Stream.kt:250) ~[?:?]
        at okhttp3.internal.http2.Http2ExchangeCodec.cancel(Http2ExchangeCodec.kt:122) ~[?:?]
        at okhttp3.internal.connection.Exchange.detachWithViolence(Exchange.kt:161) ~[?:?]
        at okhttp3.internal.connection.RealCall.exitNetworkInterceptorExchange$okhttp(RealCall.kt:424) ~[?:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:133) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[?:?]
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[?:?]
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:202) ~[?:?]
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:142) ~[?:?]
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:125) ~[?:?]
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:481) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[18:25:00 ERROR]: [net.dv8tion.jda.internal.requests.RateLimiter] Encountered exception trying to execute request
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:519) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:118) ~[?:?]
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:273) ~[?:?]
        at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259) ~[?:?]
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:261) ~[?:?]
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:142) ~[?:?]
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:125) ~[?:?]
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:481) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by freya022** [comment]
The issue isn't about not being able to send the file but rather you reloaded your plugin while JDA is still running, which caused issues.

**Comment by Andrei0016** [comment]
Thanks!

**Comment by Andrei0016** [comment]
Ok also I saw that my slash commands where not being created.
` @Override
    public void onEnable() {
        messageList.add("[" + new Date(System.currentTimeMillis()) + "] " + "Server Started");
        try {
            loadBot();
        } catch (LoginException e) {
            e.printStackTrace();
        }

        saveDefaultConfig();

        pm.registerEvents(new eventLogger(bot, messageList), this);
        Guild guild = bot.getGuildById("988851553534345216");
        if (guild != null) {
            guild.upsertCommand("getLog", "Use this to get the server log").queue();
            guild.upsertCommand("clearLog", "Use this to clear server log").queue();
        }
    }`

**Comment by freya022** [comment]
You should have made it so it would have warned you if the guild was null

As i've seen this piece of code in videos, I'd advise not to follow YouTube tutorials as they're quickly outdated and often do not show good practises

**Comment by Andrei0016** [comment]
well I placed it there because I was getting a warning so I auto completed using the editor

**Comment by Andrei0016** [comment]
Well everything works so I will close the report.
