### ISSUE TITLE
JDA throws random stream closed IOException

### ISSUE THREAD

**Issue by MandarinSmell** [DV8FromTheWorld/JDA#2174]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

I've been trying to resolve this problem for days now, I looked Stackoverflow, pull requests, issue reports, but couldn't get quite satisfied answer from them. So I built a bot which provides information about one mobile game. 

For some commands, it needs to generate image files to improve visuals. Since these generated files don't need to be cached or stored, meaning that they are just temporary files, I delete them whenever bot could send message successfully. Now problem here appears, I really can't give good example to reproduce this, but when it gets rate-limited by Discord, if message sent contains file, JDA randomly throws IOException with stream closed error.

I can't get exact way to reproduce this problem, stack trace gives me something related with `RateLimiter`, so excuse me that above statements are purely guessing, and my lack of deep knowledge about JDA structure or Discord data... Code example below is one of basic format that I use in my codes; I send message (`sendMessage`) with file (`addFile`), and call `queue()` message. Since `queue` message can provide listener for when message successfully got sent, or failed to, I add file deletion methods in there, so that bot can delete temporary files only when message sending task is fully done.

This error happens also when I obtain `Message` instance by calling `complete()` as well. I thought it *could* be problem related with these temporary files, so I made bot delete them with 5 seconds delay. It could be just that 5 seconds weren't enough, but such delayed deletion couldn't solve problem.

My bot is open source

[Adapter](https://github.com/battlecatsultimate/PackPack/blob/main/src/main/java/mandarin/packpack/AllEventAdapter.java) that I implemented is here
One of command which caused this problem is [here](https://github.com/battlecatsultimate/PackPack/blob/main/src/main/java/mandarin/packpack/commands/data/StageImage.java)
or [here](https://github.com/battlecatsultimate/PackPack/blob/main/src/main/java/mandarin/packpack/supporter/bc/EntityHandler.java) from [line 225](https://github.com/battlecatsultimate/PackPack/blob/f77a97c523649c81f76219b638d33d6c11c4fa0a/src/main/java/mandarin/packpack/supporter/bc/EntityHandler.java#L215)

I... can't suggest or provide what should happen because I actually don't know if I'm using API incorrectly, but I can guess that such problem shouldn't be appeared, or handled by JDA API itself. I will wait for answer, thanks for reading these

### Code Example for Reproduction Steps

```java
//Use this method in "onMessageReceived" for "ListnerAdapter" class
public void tryToReplicate(GenericMessageEvent event) {
    MessageChannel ch = event.getChannel();

    //This is merely example
    //My actual code doesn't spam command like this, this is just for trying to replicate problem
    //Basically spamming message with file to trigger rate-limit
    for(int i = 0; i < 20; i++) {
        File f = generateFile(); //Generate any temporary file

        ch.sendMessage("File")
            .addFile(f, "Example.txt")
            .queue(m -> {
                if(f.exist() && !f.delete()) {
                    System.out.println("failed to delete file : "+f.getAbsolutePath());
                }
            }, e -> {
                e.printStackTrace();

                if(f.exist() && !f.delete()) {
                    System.out.println("failed to delete file : "+f.getAbsolutePath());
                }
            });
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder builder = JDABuilder.createDefault(TOKEN);

builder.setEnabledIntents(
        GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_EMOJIS, GatewayIntent.GUILD_MESSAGES, 
        GatewayIntent.GUILD_MESSAGE_REACTIONS, GatewayIntent.DIRECT_MESSAGES, GatewayIntent.DIRECT_MESSAGE_REACTIONS
);
builder.disableCache(CacheFlag.VOICE_STATE);
builder.setActivity(Activity.playing(develop ? dev : normal));
builder.addEventListeners(new AllEventAdapter());

JDA client = builder.build();

//Check my github source link below, line 48 for detailed further codes
//https://github.com/battlecatsultimate/PackPack/blob/main/src/main/java/mandarin/packpack/PackBot.java
```

### Exception or Error

```yesyes
net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.io.IOException
	at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:185)
	at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
	at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:273)
	at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:255)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:142)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:125)
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:481)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.IOException: Stream Closed
	at java.base/java.io.FileInputStream.readBytes(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:273)
	at okio.InputStreamSource.read(JvmOkio.kt:90)
	at okio.Buffer.writeAll(Buffer.kt:1642)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:236)
	at net.dv8tion.jda.internal.utils.BufferedRequestBody.writeTo(BufferedRequestBody.java:60)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
	at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:202)
	... 9 more
Caused by: net.dv8tion.jda.api.exceptions.ContextException
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:198)
	at mandarin.packpack.commands.data.StageImage.handleLast(StageImage.java:126)
	at mandarin.packpack.commands.data.StageImage.doSomething(StageImage.java:83)
	at mandarin.packpack.commands.ConstraintCommand.lambda$execute$1(ConstraintCommand.java:129)
	... 1 more
```

**Comment by freya022** [comment]
You should store your images in memory instead of creating temporary files and having to manage them. The exception points to a FileInputStream being closed, so probably your file got deleted or whatever.

For that you can use a ByteArrayOutputStream, tell ImageIO to write in it, get the byte array from the ByteArrayOutputStream and pass the byte array to JDA

If it doesn't solve the issue i invite you to join the [discord server](https://discord.gg/jda)

**Comment by MandarinSmell** [comment]
Is it not safe to delete file in lambda funtion of `queue`? Doesn't it mean that when this lambda function is called, it's fine to delete generated file because it means JDA has done sending message task successfully? It doesn't delete files outside of this lambda function. If it's related with caching, is there any way to listen that full task including this caching is done?

Also I don't prefer sending raw byte data because usually this gives critical effect on memory side, and the hosting server that I'm running doesn't have that large RAM size because I'm developing/hosting this bot just for experiences as developer, with the fact that image usually has large file size, not like 1~10KB just like usual text files, etc.

**Comment by MinnDevelopment** [comment]
Multiple things here:

- Your stacktrace does not match [the latest version](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/internal/utils/BufferedRequestBody.java#L60)
- We always read the entire file into memory, before sending it. Otherwise, retrying is impossible.
- The file *can* be safely deleted after the request is done in the queue callback, since we already made a copy into memory.

**Comment by MandarinSmell** [comment]
Okay, for the first point, I now noticed that alpha 13 was released 10 days ago, let me use it, and I will notice you if problem persists as soon as possible. 

For third point, so it means that it's mostly safe to delete file as long as deletion is done in callbacks, noted. Is it also safe to delete file after calling `complete()` as well? For example,

```java
File f = generateFile();

try {
    Message m = ch.sendMessage("File")
        .addFile(f, "file.txt")
        .complete();
    
    //Doing something...
} catch(Exception e) {
    e.printStacktrace();
} finally {
    if(f.exists() && !f.delete() {
        System.out.println("Failed to delete file");
    }
}
```

**Comment by MinnDevelopment** [comment]
> Is it also safe to delete file after calling complete() as well?

The `complete()` method essentially just blocks the current thread until the queue callback is run. So doing something after `complete()` returns, is identical to doing something in the queue callback, in terms of timing.

I do not think that the issue here could be caused by the delete in the queue callback, unless the files share the same name. This could be possible, if you have an unsafe way of generating unique filenames. I saw in your code, that you simply have some static method which loops until a file that doesn't exist is created, which is in theory unsafe.

As it was already recommended, you should simply store the file in memory using a byte[], since that is ultimately what JDA will do either way. If you don't want to do it that way, you should use a more appropriate way of generating temp files, such as [Files.createTemporaryFile(...)](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempFile-java.nio.file.Path-java.lang.String-java.lang.String-java.nio.file.attribute.FileAttribute...-).

**Comment by MandarinSmell** [comment]
I honestly felt that way, it's unlikely that my bot is in that many servers, so threads that I created caused conflicts among file names, but it's theoretically still possible. I know `Files.createTempFile()` method, but I need to store files in this `temp` folder though, so that I can manage files which got generated by bot easily for debugging, or whatever purposes are. It's just my preference, I will try to improve safety of file handling instead.

For now, bot stopped sending stream closed error after I updating API. But since there are still problem that there can be name conflict among files due to how I'm generating temp files, I will let you know after solving this problem

**Comment by MinnDevelopment** [comment]
> I know Files.createTempFile() method, but I need to store files in this temp folder

The method I linked lets you specify a directory as the first parameter, that should work. `Files.createTempFile(Paths.get("./temp"), "image", ".png")`

Which creates a file like this:

```
jshell> Files.createTempFile(Paths.get("./temp"), "image", ".png")
$1 ==> ./temp/image6700668970453732818.png
```

**Comment by MinnDevelopment** [comment]
I think this is the bug that was fixed [here](https://github.com/DV8FromTheWorld/JDA/commit/4f7b413a9c7b96a541eaf269dea95290f529f503). We used to close the stream too early in an older version, this shouldn't be happening anymore on the current release.
