### ISSUE TITLE
ThreadChannel perm checks checking for Manage_Channel

### ISSUE THREAD

**Issue by Vrontis** [DV8FromTheWorld/JDA#2188]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

JDA should _only_ check for the Manage_Threads permission, on edit/delete related perm checks on ThreadChannels, not also for Manage_Channel.
Tested needed permissions on regular Discord client & on non-JDA bots.

### Code Example for Reproduction Steps

```java
public void threadPermExample(ThreadChannel threadChannel) {
    // Here the .getManager() throws the the InsufficientPermissionException, effectively calling
    // net.dv8tion.jda.internal.managers.channel.ChannelManagerImpl#checkPermissions
    threadChannel.getManager().setArchived(false).complete();

    // Here it's .delete()
    // net.dv8tion.jda.internal.entities.mixin.channel.middleman.GuildChannelMixin#delete
    threadChannel.delete().queue();
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
api = JDABuilder.createDefault(config.getAuthToken()).addEventListeners(
                client,
                new GuildListener(),
                new ThreadListener()
        ).enableIntents(GatewayIntent.GUILD_MEMBERS).build();
```

### Exception or Error

```yesyes
net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MANAGE_CHANNEL
	at net.dv8tion.jda.internal.managers.channel.ChannelManagerImpl.checkPermissions(ChannelManagerImpl.java:575)
	at net.dv8tion.jda.internal.managers.channel.ChannelManagerImpl.<init>(ChannelManagerImpl.java:79)
	at net.dv8tion.jda.internal.managers.channel.concrete.ThreadChannelManagerImpl.<init>(ThreadChannelManagerImpl.java:27)
	at net.dv8tion.jda.internal.entities.ThreadChannelImpl.getManager(ThreadChannelImpl.java:280)
	at dev.vrontis.quickbot.listener.GuildListener.lambda$onChannelUpdateArchived$0(GuildListener.java:38)
```

**Comment by MinnDevelopment** [comment]
Resolved by 5.0.0-alpha.19
