### ISSUE TITLE
Problem with sending file with interaction replies

### ISSUE THREAD

**Issue by MandarinSmell** [DV8FromTheWorld/JDA#2189]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

When I use `GenericComponentInteractionEvent`, or `GenericCommandInteractionEvent`, if I call `addFile(File f, String name)` method and queue/complete it, JDA throws an error like stack trace below. It says field "type" is missing, so I thought that I missed something, but I couldn't find any method related with this `type`, so I'm creating new issues here

It wasn't like this before migrating 5.0.0 alpha 16. I updated JDA API since I saw that now JDA can support voice message channel (Good job, really loved that your team supports new Discord's feature as quick as possible). So I think it shouldn't throw such error unless I'm really missing something. I will leave stack trace below

You may remember me, but [link](https://github.com/battlecatsultimate/PackPack) here is my bot's github project and it's open source. You can check my codes, so that it will be helpful for you to debug this problem.

### Code Example for Reproduction Steps

```java
//In ListenerAdapter...
@Override
public void onGenericComponentInteractionCreate(@NotNull GenericComponentInteractionCreateEvent event) {
  File f = generateFile();

  event.deferReply()
    .addFile(f, "test.txt")
    .queue(); //or .complete();

  //or
  event.reply("Test Message")
    .addFile(f, "test.txt")
    .queue(); //or complete();
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder builder = JDABuilder.createDefault(TOKEN);

builder.setEnabledIntents(
        GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_EMOJIS_AND_STICKERS, GatewayIntent.GUILD_MESSAGES, 
        GatewayIntent.GUILD_MESSAGE_REACTIONS, GatewayIntent.DIRECT_MESSAGES, GatewayIntent.DIRECT_MESSAGE_REACTIONS, 
        GatewayIntent.MESSAGE_CONTENT
);
builder.disableCache(CacheFlag.VOICE_STATE);
builder.setActivity(Activity.playing(develop ? dev : normal));
builder.addEventListeners(new AllEventAdapter());

JDA client = builder.build();

//More code at
//https://github.com/battlecatsultimate/PackPack/blob/26ed022b1523d9cdbc9b3fcbc4dd40e780e738a2/src/main/java/mandarin/packpack/PackBot.java#L48
```

### Exception or Error

```yesyes
net.dv8tion.jda.api.exceptions.ErrorResponseException: 50035: Invalid Form Body
	- TAG_FIELD_MISSING: Field "type" is required to determine the model type.
	at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:185)
	at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
	at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:273)
	at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.handleResponse(InteractionCallbackImpl.java:151)
	at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:239)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:143)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:126)
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:481)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: net.dv8tion.jda.api.exceptions.ContextException
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:198)
	at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:116)
	at mandarin.packpack.commands.bc.Background.performButton(Background.java:46)
	at mandarin.packpack.supporter.server.holder.StageInfoButtonHolder.performInteraction(StageInfoButtonHolder.java:127)
	at mandarin.packpack.supporter.server.holder.StageInfoButtonHolder.performInteraction(StageInfoButtonHolder.java:1)
	at mandarin.packpack.AllEventAdapter.onGenericInteractionCreate(AllEventAdapter.java:803)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:131)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:83)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by MandarinSmell** [comment]
Pretty sure this github repo's ReadMe.md guides users to follow [this way](https://github.com/battlecatsultimate/PackPack/blob/26ed022b1523d9cdbc9b3fcbc4dd40e780e738a2/src/main/java/mandarin/packpack/PackBot.java#L48)

If I'm supposed to use that, which author do I have to follow, and shouldn't markdown file guide us that way?

**Comment by freya022** [comment]
The fix has not been released yet so you have to use jitpack, which the Readme also tells. You can just go on the jitpack website and select the master branch, it shouldn't change that much

For maven, latest on `master` is:
```xml
<dependency>
    <groupId>com.github.DV8FromTheWorld</groupId>
    <artifactId>JDA</artifactId>
    <version>efe995de2d</version>
</dependency>
```

**Comment by MandarinSmell** [comment]
I thought those commits are included in alpha 16 due to [this](https://github.com/DV8FromTheWorld/JDA/compare/v5.0.0-alpha.16...master)?

**Comment by freya022** [comment]
No, this diff shows what commits from `master` are missing from alpha 16

**Comment by MandarinSmell** [comment]
Yeah, I see stuffs now. So it wasn't that alpha 16 contained the latest commits, my bad. Okay then, I will use jitpack way while waiting for new releases. Thanks for the help

**Comment by MinnDevelopment** [comment]
Fixed in alpha 17
