### ISSUE TITLE
[v4] NPE retrieving webhooks from guild

### ISSUE THREAD

**Issue by granny** [DV8FromTheWorld/JDA#2207]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

JDA should not throw an NPE when attempting to retrieve all webhooks from a guild. The NPE appears when it attempts to parse a webhook from a VoiceChannel

### Code Example for Reproduction Steps

```java
public class Main {
    public static void main(String[] args) throws Exception {
        JDA jda = JDABuilder.createDefault("XXXXXXXXXXXX.XXXX.XXXXXXXXXX").build();

        jda.awaitReady();

        // one of these guilds must have a voice channel that has a webhook integration for the NPE to appear
        jda.getGuilds().forEach(guild -> guild.retrieveWebhooks().complete());
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDA jda = JDABuilder.createDefault("XXXXXXXXXXXX.XXXX.XXXXXXXXXX").build();
```

### Exception or Error

```yesyes
[JDA RateLimit-Worker 1] ERROR JDA - Error creating webhook from json
java.lang.NullPointerException: Tried to create Webhook for an un-cached TextChannel! WebhookId: 1006462437689655337 ChannelId: 1006462417309540402 GuildId: 680676225123090452
	at net.dv8tion.jda.internal.entities.EntityBuilder.createWebhook(EntityBuilder.java:1661)
	at net.dv8tion.jda.internal.entities.EntityBuilder.createWebhook(EntityBuilder.java:1648)
	at net.dv8tion.jda.internal.entities.GuildImpl.lambda$retrieveWebhooks$18(GuildImpl.java:514)
	at net.dv8tion.jda.internal.requests.RestActionImpl.handleSuccess(RestActionImpl.java:278)
	at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:268)
	at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:237)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:141)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:124)
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by V-Play-Games** [comment]
I'd recommend updating to the latest alpha version and see if the error persists

**Comment by DxsSucuk** [comment]
Isn't this about v4?
So switching to the latest v5 alpha could fix it but would need code migration.

**Comment by MinnDevelopment** [comment]
This is working as intended on v4. You will have to update to v5 to access those webhooks, specifically for voice channels.

**Comment by DxsSucuk** [comment]
Shouldn't there be some way for JDA v4 to ignore voicechannels webhooks cause otherwise you can not get every webhook of an guild.

**Comment by granny** [comment]
> This is working as intended on v4. You will have to update to v5 to access those webhooks, specifically for voice channels.

I'm not interested in using webhooks for voice channels so that's not an option. How would I go about handling that error?

**Comment by MinnDevelopment** [comment]
You don't need to handle it, its just caught and logged. You still get all the other webhooks in the callback.

The code is here:

https://github.com/DV8FromTheWorld/JDA/blob/c2d16c83e2c8d1fc853fb494639040cf5d86fd95/src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java#L512-L519

**Comment by granny** [comment]
I plan on migrating to v5 when it's out of alpha. I am not interested in using webhooks in voice channels for now, and I'd like to hide the error since it just adds confusion to those who use my app.

**Comment by V-Play-Games** [comment]
> I plan on migrating to v5 when it's out of alpha. I am not interested in using webhooks in voice channels for now, and I'd like to hide the error since it just adds confusion to those who use my app.

Well, as a work around, you can create a list of text/news channels and retrieve their webhooks individually and combine it into a list. Also see RestAction#allOf. You might need it
