### ISSUE TITLE
Guild does not have a self member

### ISSUE THREAD

**Issue by DevLEMCraft** [DV8FromTheWorld/JDA#2342]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

Change the Server Icon

### Code Example for Reproduction Steps

```java
GuildManager guildManager = guild.getManager();
		
		File file = new File("D:\\Bilder-Videos\\Logos\\Halloween PB.png");
		
		try {
			guildManager.setIcon(Icon.from(file)).queue();
		} catch (IOException e) {
			e.printStackTrace();
		}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
DefaultShardManagerBuilder builder = DefaultShardManagerBuilder.createDefault(TOKEN);
```

### Exception or Error

```yesyes
java.lang.IllegalStateException: Guild does not have a self member
	at net.dv8tion.jda.internal.entities.GuildImpl.getSelfMember(GuildImpl.java:650)
	at net.dv8tion.jda.internal.managers.GuildManagerImpl.checkPermissions(GuildManagerImpl.java:376)
	at net.dv8tion.jda.internal.managers.GuildManagerImpl.<init>(GuildManagerImpl.java:61)
	at net.dv8tion.jda.internal.entities.GuildImpl.getManager(GuildImpl.java:982)
	at de.lemcraft.lemcord.bot.Bot.Bot(Bot.java:38)
	at de.lemcraft.lemcord.bot.Bot.BotBuilder(Bot.java:25)
	at de.lemcraft.lemcord.bot.Main.main(Main.java:9)
```

**Comment by MinnDevelopment** [comment]
Where is this Guild coming from? Are you sure your bot is in the guild? Please provide proper reproduction steps, your entire builder code, and a full explanation of your issue. You have omitted too much information.

**Comment by MinnDevelopment** [comment]
Closing due to inactivity. If you have more details to properly analyze the problem, feel free to open a new issue.

To properly address issues like this, we need to know more details about the origin of the guild and how it was used/acquired. As is, this issue provides no usable details and cannot be solved.
