### ISSUE TITLE
NullPointerException when looping through Guilds

### ISSUE THREAD

**Issue by Akio08** [DV8FromTheWorld/JDA#236]
I'm back here... (sorry :/ )

Well, in the #235 issue, it was said that `In a normal situation, Guilds are already available and loaded when the ReadyEvent is dispatched`

But when I run this code :

```java
@Override
    public void onEvent(Event event)
    {
        if(event instanceof ReadyEvent){
            this.checkData();
            this.commands.put("!help", new HelpCommand(this));
            for(Guild g : this.myBot.getGuilds()){
                this.guilds.put(g, new JGuild(g)); // Assoc. Guild with a JGuild (custom database link)
            }
        }
    }
```
I have this (_everytime_):
```
[19:19:58] [Info] [JDA]: Finished Loading!
[19:19:59] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[19:19:59] [Fatal] [JDA]: Encountered an exception:
[19:19:59] [Fatal] [JDA]: java.lang.NullPointerException
        at ovh.akio.discord.bot.Mayushii.onEvent(Mayushii.java:53)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.core.requests.WebSocketClient.ready(WebSocketClient.java:128)
        at net.dv8tion.jda.core.handle.ReadyHandler.guildLoadComplete(ReadyHandler.java:165)
        at net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:191)
        at net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$93(GuildCreateHandler.java:45)
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuildSecondPass(EntityBuilder.java:337)
        at net.dv8tion.jda.core.handle.GuildMembersChunkHandler.handleInternally(GuildMembersChunkHandler.java:59)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:688)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:437)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
```

Mayushii.java:53 : `for(Guild g : this.myBot.getGuilds()){`

Available and loaded but null ? huh... slightly annoying :/

It's possible to get the Guilds' list when JDA is ready without this error ?

**Comment by DinosParkour** [comment]
have you initialized the myBot field?

**Comment by Akio08** [comment]
Yes, seems logic, the event is registered

**Comment by DinosParkour** [comment]
The only thing on that line that could throw a NPE is probably you failing to set the bot instance after everything gets set up.. I don't see any code related to `myBot` in the ReadyEvent so that's what I'd assume.
Is there anywhere I can see the source code of the entire class?

**Comment by Akio08** [comment]
The bot is connected to my server and receive other event, so I don't know why it throw a NPE...

```java
private JDA myBot;

    public Mayushii(String key){
        try{
            this.myBot = new JDABuilder(AccountType.BOT).setToken(key).addListener(this).buildBlocking();
            this.myBot.addEventListener(new MessageListener(this));
            this.myBot.addEventListener(new GuildAvailableListener());
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }

    public Command getCommandExecutor(String command){
        return this.commands.get(command);
    }

    @Override
    public void onEvent(Event event)
    {
        if(event instanceof ReadyEvent){
            this.checkData();
            this.commands.put("!help", new HelpCommand(this));
            while(this.myBot.getGuilds().size() == 0){
                System.out.println("0 Guilds");
            }
            while(this.myBot.getGuilds().get(0) == null){
                System.out.println("First is null");
            }
            for(Guild g : this.myBot.getGuilds()){
                this.guilds.put(g, new JGuild(g)); // Assoc. Guild with a JGuild (custom database link)
            }
        }
    }
```

And I have a NPE on `while(this.myBot.getGuilds().size() == 0){`

And the MessageListener is working fine...

**Comment by DinosParkour** [comment]
I *think* that the ReadyEvents gets fired at the same time as buildBlocking() returns the jda instance to your `myBot` variable. That's what makes the code not work in your main class, while it remains functional in other classes that do not depend on the JDA object you create upon building.
I would really recommend against using variables to store JDA-related objects, as they might get invalidated on disconnect etc etc. In this case, you can easily use `e.getJDA()` to get the jda instance you need.
Final note, take a look at the [examples directory](https://github.com/DV8FromTheWorld/JDA/blob/master/src/examples/java/MessageListenerExample.java) for a guideline on how to listen for events so that you don't have to check the type of event (instanceof) every time you want to execute specific code.

**Comment by Akio08** [comment]
Even with the _event.getJDA()_ , I have a NPE.
I know how to use the ListenerAdapter, I'm using this method for my MessageListener :
```java
public class MessageListener extends ListenerAdapter
```

But I'm using the _onEvent()_ method to test my event (and then I create a class for it).
I really don't know why I have a NPE.

**Comment by Akio08** [comment]
Problem solved when I call 
```java
private void waitForGuild(JDA a){
        while (a.getGuilds() == null){
            System.out.println("List is null");
        }
        while (a.getGuilds().size() == 0){
            System.out.println("List is empty");
        }
        while (a.getGuilds().get(0) == null){
            System.out.println("First Guild is null");
        }
    }
```
And nothing in the console log... wow.

**Comment by jagrosh** [comment]
Don't use buildBlocking, use buildAsync instead, and add your listeners to the JDABuilder
The issue here is that the ReadyEvent can fire before the buildBlocking function returns like @DinosParkour said. Usin buildAsync will fix this issue.
