### ISSUE TITLE
Exception in thread "JDA MainWS-ReadThread" java.lang.NoClassDefFoundError: com/neovisionaries/ws/client/WebSocketError

### ISSUE THREAD

**Issue by Miniontoby** [DV8FromTheWorld/JDA#2386]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

To not give any exception

### Code Example for Reproduction Steps

```java
N/A
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDA jda = JDABuilder.createDefault(token)
    .enableIntents(GatewayIntent.MESSAGE_CONTENT)
    .setActivity(Activity.playing("Mindustry"))
    .build();

jda.addEventListener(new DiscordBot(channelid));

try {
    jda.awaitReady();
} catch (InterruptedException e) {}
```

### Exception or Error

```yesyes
Exception in thread "JDA MainWS-ReadThread" java.lang.NoClassDefFoundError: com/neovisionaries/ws/client/WebSocketError
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:69)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.ClassNotFoundException: com.neovisionaries.ws.client.WebSocketError
        at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at mindustry.core.Platform$1.loadClass(Platform.java:36)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at mindustry.core.Platform$1.loadClass(Platform.java:36)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 2 more
Exception in thread "JDA MainWS-WriteThread" java.lang.NoClassDefFoundError: com/neovisionaries/ws/client/WebSocketError
        at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:60)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by Andre601** [comment]
Did you actually shade in JDA?

**Comment by Miniontoby** [comment]
> Did you actually shade in JDA?

What does that mean?

**Comment by MinnDevelopment** [comment]
See the [troubleshooting guide](https://jda.wiki/using-jda/troubleshooting/#noclassdeffounderror-or-classnotfoundexception-on-startup). I would recommend to follow the [setup guide](https://jda.wiki/setup/intellij/).

**Comment by Miniontoby** [comment]
I just use maven-assembly-plugin

**Comment by Andre601** [comment]
> I just use maven-assembly-plugin

As Minn said, read the throubleshooting guide and the setup guide. They help you solve this issue.

**Comment by Miniontoby** [comment]
https://edugit.org/Miniontoby/mindiscory/-/tree/main/maven_version

I already have the shade plugin, but I use the assembly plugin for my .jar that I use...

**Comment by Miniontoby** [comment]
Oke, I will start using the shade plugin

**Comment by Miniontoby** [comment]
@MinnDevelopment @Andre601 
> See the [troubleshooting guide](https://jda.wiki/using-jda/troubleshooting/#noclassdeffounderror-or-classnotfoundexception-on-startup). I would recommend to follow the [setup guide](https://jda.wiki/setup/intellij/).

I have followed it and am now using the shade plugin, BUT IT STILL GIVES ME THE ERROR!

**Comment by Andre601** [comment]
Then please provide actual info we can work with such as your latest pom.xm version, the maven command you used and steps to encounter this.

Also, no need to WRITE TEXT IN CAPS or mention us. We follow this issue and get notified for posts made in it.

**Comment by Miniontoby** [comment]
> Then please provide actual info we can work with such as your latest pom.xm version, the maven command you used and steps to encounter this.
> 
> Also, no need to WRITE TEXT IN CAPS or mention us. We follow this issue and get notified for posts made in it.

The code is viewable at https://edugit.org/Miniontoby/mindiscory/-/tree/main/maven_version 
To run the code, you need to make mindustry server and then you put the target/MinDiscory.jar into the `<SERVER_PATH>/config/mods/` folder

(about the mention, I though github might stop notifications when issue is closed)
