### ISSUE TITLE
Got an unexpected Json-parse error.

### ISSUE THREAD

**Issue by megoRU** [DV8FromTheWorld/JDA#2394]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [ ] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

I understand it came from the discord api

### Code Example for Reproduction Steps

```java
I have no idea
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder jdaBuilder = JDABuilder.createDefault(Config.getTOKEN());
List<GatewayIntent> intents = new ArrayList<>(
                    Arrays.asList(
                            GatewayIntent.GUILD_MESSAGES,
                            GatewayIntent.MESSAGE_CONTENT,
                            GatewayIntent.DIRECT_MESSAGES,
                            GatewayIntent.DIRECT_MESSAGE_TYPING));

            jdaBuilder.disableCache(
                    CacheFlag.CLIENT_STATUS,
                    CacheFlag.ACTIVITY,
                    CacheFlag.MEMBER_OVERRIDES,
                    CacheFlag.VOICE_STATE,
                    CacheFlag.ONLINE_STATUS);

            jdaBuilder.setAutoReconnect(true);
            jdaBuilder.setStatus(OnlineStatus.ONLINE);
            jdaBuilder.enableIntents(intents);
            jdaBuilder.setActivity(Activity.playing("Starting..."));
            jdaBuilder.setBulkDeleteSplittingEnabled(false);
            jdaBuilder.addEventListeners(new CoreBot(updateController));

            jda = jdaBuilder.build();
            jda.awaitReady();
```

### Exception or Error

```yesyes
2023-02-08T04:59:59.892Z  WARN 1 --- [inWS-ReadThread] n.d.j.internal.requests.WebSocketClient  : Got an unexpected Json-parse error. 
Please redirect the following message to the devs:
        JDA 5.0.0-alpha.22_5d13c14
        Unable to resolve value with key entity_metadata to type DataObject: null
        GUILD_SCHEDULED_EVENT_UPDATE -> 
		{"image":null,
		"privacy_level":2,
		"entity_metadata":null,
		"description":"Ловушечка",
		"entity_id":null,"scheduled_end_time":"2023-02-08T13:30:00+00:00",
		"entity_type":3,
		"sku_ids":[],
		"name":"Лова Lova Trap",
		"guild_id":"1060906470763409466",
		"creator_id":"903380664336928798",
		"id":"1072376545534025818",
		"channel_id":null,
		"status":4,
		"scheduled_start_time":"2023-02-08T13:00:00+00:00"}

net.dv8tion.jda.api.exceptions.ParsingException: Unable to resolve value with key entity_metadata to type DataObject: null
        at net.dv8tion.jda.api.utils.data.DataObject.valueError(DataObject.java:859) ~[JDA-5.0.0-alpha.22.jar!/:5.0.0-alpha.22]
        at net.dv8tion.jda.api.utils.data.DataObject.lambda$getObject$0(DataObject.java:279) ~[JDA-5.0.0-alpha.22.jar!/:5.0.0-alpha.22]
        at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
        at net.dv8tion.jda.api.utils.data.DataObject.getObject(DataObject.java:279) ~[JDA-5.0.0-alpha.22.jar!/:5.0.0-alpha.22]
        at net.dv8tion.jda.internal.handle.ScheduledEventUpdateHandler.handleInternally(ScheduledEventUpdateHandler.java:74) ~[JDA-5.0.0-alpha.22.jar!/:5.0.0-alpha.22]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[JDA-5.0.0-alpha.22.jar!/:5.0.0-alpha.22]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:965) ~[JDA-5.0.0-alpha.22.jar!/:5.0.0-alpha.22]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:851) ~[JDA-5.0.0-alpha.22.jar!/:5.0.0-alpha.22]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:829) ~[JDA-5.0.0-alpha.22.jar!/:5.0.0-alpha.22]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1004) ~[JDA-5.0.0-alpha.22.jar!/:5.0.0-alpha.22]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar!/:na]
```

**Comment by MinnDevelopment** [comment]
This seems to still be an issue, I'm currently investigating. Oddly enough, this event seems to have no location information. This might be a discord bug, since `entity_metadata` should be required for `entity_type=3`. According to the [documentation](https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object-field-requirements-by-entity-type).

**Comment by MinnDevelopment** [comment]
This will be fixed in the next release.
