### ISSUE TITLE
Guild#ban don't work

### ISSUE THREAD

**Issue by IDEEESS** [DV8FromTheWorld/JDA#2402]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

**Guild#ban** don't work . 

### Code Example for Reproduction Steps

```java
@Override
    public void onSlashCommandInteraction(SlashCommandInteractionEvent event) {
        if (event.getName().equals("ping")) {
            event.reply("Pong !").queue(); // reply immediately
        } else if (event.getName().equals("ban")) {
            User baned = (User) event.getOption("user").getAsMember();
            if (baned == event.getUser()){
                event.reply("**Vous ne pouvez pas vous bannir** "+event.getUser().getAsMention()).queue();
                return;
            };
            if (baned == event.getJDA().getSelfUser()) {
                event.reply("**Vous ne pouvez pas me bannir avec mes commandes** "+event.getUser().getAsMention()).queue();
                return;
            }
            String reason = Objects.requireNonNull(event.getOption("reason")).getAsString();
            event.reply("@everyone , le joueur **" + baned.getAsTag() + "** a été banni par **" + event.getUser().getName() + "** pour la raison : ***" + reason + "***").queue();
            event.getGuild().ban(UserSnowflake.fromId(baned.getId()),0,null).reason(event.getUser().getName() + " : " + reason).queue();

            //event.getUser().getName() + " : " + reason
        }
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder.createDefault("token[ah ah]") // don't use the deprecated constructor
                .addEventListeners(new Main())
                .setActivity(Activity.of(Activity.ActivityType.COMPETING,"IDEEESS","https://www.youtube.com/channel/UCJmihYJf0DNkr8xN4dVWwCA"))
                .setStatus(OnlineStatus.ONLINE)
                .build()
                .updateCommands().addCommands(
                        Commands.slash("ping","Répond au Ping"),
                        Commands.slash("ban","Ban un joueur")
                                .addOption(OptionType.USER,"user","Choisit un utilisateur",true,false)
                                .addOption(OptionType.STRING,"reason","Définit une raison",true,false)
                                .setDefaultPermissions(DefaultMemberPermissions.enabledFor(Permission.BAN_MEMBERS))
                ).queue();
```

### Exception or Error

```yesyes
[JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
java.lang.ClassCastException: class net.dv8tion.jda.internal.entities.MemberImpl cannot be cast to class net.dv8tion.jda.api.entities.User (net.dv8tion.jda.internal.entities.MemberImpl and net.dv8tion.jda.api.entities.User are in unnamed module of loader 'app')
	at fr.ideeess.bot.Main.onSlashCommandInteraction(Main.java:51)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:425)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:181)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:112)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:83)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:983)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:869)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:847)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1022)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by Almighty-Satan** [comment]
This is not a JDA issue. 
Do `User baned = event.getOption("user").getAsUser();` instead of `User baned = (User) event.getOption("user").getAsMember();`

**Comment by IDEEESS** [comment]
How ban definitly the user ?

**Comment by MinnDevelopment** [comment]
What does "ban definitely" mean? Also in the future please use discussions for questions and help.

**Comment by IDEEESS** [comment]
The user can't join the server discord but he can join the serv if he is unban

**Comment by MinnDevelopment** [comment]
The [SlashBotExample](https://github.com/DV8FromTheWorld/JDA/blob/master/src/examples/java/SlashBotExample.java) has a ban command that should answer all your questions. A ban always prevents users from rejoining and bans are always indefinite.
