### ISSUE TITLE
JDA sending two replies upon one interaction

### ISSUE THREAD

**Issue by TollerNamen** [DV8FromTheWorld/JDA#2403]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

JDA should reply to an interaction once with the 'deferReply' method and then send a message upon the hook with like, for example, the server avatar. Instead, it sends two messages with the hook: the first is a reply upon my slash command and the second message replies weirdly on the first message. The client outputs an 'IllegalStateError', (see the error message) upon these two messages. Also I tried to register such event with a eventkey, like ChatGPT by OpenAI, (suggested and implemented) to try and resolve the issue by filtering the 2nd 'interaction', if it has the same eventkey, but this doesn't resolve the issue.

### Code Example for Reproduction Steps

```java
private final Set<String> processedEvents = new HashSet<>();

@Override
    public void onSlashCommandInteraction(SlashCommandInteractionEvent event) {
        String eventKey = getEventKey(event);
        if (processedEvents.contains(eventKey)) {
            System.out.println(eventKey);
            // Event has already been processed, ignore it
            return;
        }
        processedEvents.add(eventKey);
        event.deferReply().setEphemeral(false).queue();
        if (event.getName().equals("misc_user-avatar"))
        {
            OptionMapping userOption = event.getOption("user");
            if (userOption != null)
            {
                event.getHook().sendMessage("Avatar: " + userOption.getAsMember().getEffectiveAvatarUrl()).queue();
            } else
            {
                event.getHook().sendMessage("Avatar: " + event.getMember().getEffectiveAvatarUrl()).queue();
            }
        }
        else if (event.getName().equals("misc_server-avatar"))
        {
            event.getHook().sendMessage("Avatar: " + Objects.requireNonNull(event.getGuild()).getIconUrl()).queue();
        }
    }
    private String getEventKey(SlashCommandInteractionEvent event) {
        return event.getFullCommandName() + ":" + event.getUser().getId() + ":" +  event.getCommandId();
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
jda = JDABuilder.createDefault(token_development) /* 'token_development' is a variable I use */
                .setStatus(OnlineStatus.ONLINE)
                .setActivity(Activity.playing("mit Botinteraktionen"))
                .setChunkingFilter(ChunkingFilter.ALL)
                .setMemberCachePolicy(MemberCachePolicy.ALL)
                .enableIntents(GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_PRESENCES, GatewayIntent.GUILD_VOICE_STATES, GatewayIntent.DIRECT_MESSAGE_TYPING,
                        GatewayIntent.DIRECT_MESSAGES,GatewayIntent.GUILD_MESSAGES, GatewayIntent.GUILD_MESSAGE_REACTIONS, GatewayIntent.GUILD_MESSAGE_TYPING,
                        GatewayIntent.GUILD_PRESENCES, GatewayIntent.MESSAGE_CONTENT)
                //.enableCache(CacheFlag.ACTIVITY);
                .addEventListeners(new contextmenutest())
                .addEventListeners(new basemessage())
                .addEventListeners(new contextmenutest())
                .addEventListeners(new createTextchannel())
                .addEventListeners(new modal())
                //.addEventListeners(new Interface())
                .build();
```

### Exception or Error

```yesyes
[JDA MainWS-ReadThread] ERROR RestAction - RestAction queue returned failure
java.lang.IllegalStateException: This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction once!
	at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.tryAck(InteractionCallbackImpl.java:57)
	at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:64)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
	at test.contextmenutest.onSlashCommandInteraction(contextmenutest.java:74)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:424)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:171)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:112)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:83)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:984)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:870)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:848)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1023)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by Xirado** [comment]
You're registering the listener twice

**Comment by TollerNamen** [comment]
okay uhm sry for that, thanks for your help, uhm, i did not expect that. It seems that im blind

**Comment by Xirado** [comment]
The solution you got from ChatGPT is also very wrong and a memory leak

**Comment by TollerNamen** [comment]
well im going remove that now become unnecessary code anyways, but thanks for your information about that.
