### ISSUE TITLE
reaction.getCount() not working

### ISSUE THREAD

**Issue by leonbeer** [DV8FromTheWorld/JDA#2404]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

Get the count of the Message in a specific Private channel the bot has access to, and then delete the message, should it reach/exceed 2 reactions of the 🚫 emoji

### Code Example for Reproduction Steps

```java
public void onMessageReactionAdd(MessageReactionAddEvent event) {
        Channel channel = event.getChannel();
        if (channel.getId().equals("ID of specific channel here")){
            String Reaction = event.getReaction().getEmoji().getName();
            System.out.println(Reaction);
            if (Reaction.equals("\uD83D\uDEAB")){
                int Count = event.getReaction().getCount();
                System.out.println(Count);
                if (Count >= 2){
                    String message = event.getReaction().getMessageId();
                    event.getGuildChannel().deleteMessageById(message).queue();
                }
            }
        }
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
public class Guardian {
    private final ShardManager shardmanager;

    public Guardian() throws LoginException {
        DefaultShardManagerBuilder builder = DefaultShardManagerBuilder.createDefault("Tokenhere");
        builder.setActivity(Activity.watching("From your walls"));
        builder.setStatus(OnlineStatus.ONLINE);
        builder.enableIntents(GatewayIntent.MESSAGE_CONTENT, GatewayIntent.DIRECT_MESSAGES, GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_MESSAGE_REACTIONS, GatewayIntent.DIRECT_MESSAGE_REACTIONS);
        builder.enableCache(CacheFlag.MEMBER_OVERRIDES, CacheFlag.EMOJI);
        shardmanager = builder.addEventListeners(new ReadyEventListener(), new GlobalCommands(), new ModerationEvent(), new OnJoin(), new SlashCommandsLocal(), new OnLeave(), new OnReactionInChannelReceived(), new MessageReceived()).build();
    }

    public ShardManager getShardmanager() {
        return shardmanager;
    }

    public static void main(String[] args) {
        try {
            Guardian bot = new Guardian();
        } catch (LoginException e) {
            System.out.println("ERROR: Invalid or incomplete Bot Token");

        }

    }
}
```

### Exception or Error

```yesyes
[JDA [0 / 1] MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
java.lang.IllegalStateException: Cannot retrieve count for this MessageReaction!
	at net.dv8tion.jda.api.entities.MessageReaction.getCount(MessageReaction.java:138)
	at events.OnReactionInChannelReceived.onMessageReactionAdd(OnReactionInChannelReceived.java:14)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:424)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:171)
	at net.dv8tion.jda.internal.handle.MessageReactionHandler.handleInternally(MessageReactionHandler.java:176)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:984)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:870)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:848)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1023)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by MinnDevelopment** [comment]
This is intended and documented behavior. We cannot provide a count because Discord does not provide in the event. You have to re-retrieve the message or keep track of the count yourself.
