### ISSUE TITLE
RateLimit-Workers prevent JVM shutdown if startup fails

### ISSUE THREAD

**Issue by Bungeefan** [DV8FromTheWorld/JDA#2405]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Current Behaviour

Currently, if there is a connection problem (like DNS failing) while JDA is building/starting and therefore throws an Exception to the caller, the RateLimit-Workers are forever remaining in `Thread.State: WAITING (parking)`.
I, for example, reproduced this by using an unreachable DNS server.

### Expected Behaviour:
JDA should stop the RateLimit-Workers when failing to build/start, to allow the JVM to shut down after the exception without needing to use `System.exit`.

### Notes:

Worker Thread Dump:
```
"JDA RateLimit-Worker 1" #17 prio=5 os_prio=0 cpu=52,92ms elapsed=381,52s tid=0x00007fac30b00000 nid=0xd0ee waiting on condition  [0x00007fabf17fe000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.18/Native Method)
        - parking to wait for  <0x000000053d0053e8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.18/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.18/AbstractQueuedSynchronizer.java:2081)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.18/ScheduledThreadPoolExecutor.java:1177)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.18/ScheduledThreadPoolExecutor.java:899)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.18/ThreadPoolExecutor.java:1054)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.18/ThreadPoolExecutor.java:1114)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.18/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)

"JDA RateLimit-Worker 2" #18 prio=5 os_prio=0 cpu=2,87ms elapsed=381,50s tid=0x00007fac30b13800 nid=0xd0ef waiting on condition  [0x00007fabf13fe000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.18/Native Method)
        - parking to wait for  <0x000000053d0053e8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.18/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.18/AbstractQueuedSynchronizer.java:2081)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.18/ScheduledThreadPoolExecutor.java:1177)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.18/ScheduledThreadPoolExecutor.java:899)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.18/ThreadPoolExecutor.java:1054)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.18/ThreadPoolExecutor.java:1114)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.18/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)

```

### Code Example for Reproduction Steps

```java
N/A
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDA jda = JDABuilder.createDefault("token")
        .setAutoReconnect(true)
        .addEventListeners(listeners)
        .build();
```

### Exception or Error

```yesyes
[JDA RateLimit-Worker 1] ERROR Requester - DNS resolution failed: discord.com: Temporärer Fehler bei der Namensauflösung
net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.UnknownHostException
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:230)
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632)
	at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:397)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:323)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:293)
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1803)
	at com.example.Main.main(Main.java:36)
Caused by: java.net.UnknownHostException: discord.com: Temporärer Fehler bei der Namensauflösung
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1534)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1524)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1382)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:182)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:144)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:127)
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:492)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: net.dv8tion.jda.api.exceptions.ContextException
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:73)
	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:212)
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:222)
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632)
	at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:397)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:323)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:293)
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1803)
	at com.example.Main.main(Main.java:36)
```

**Comment by MinnDevelopment** [comment]
This should be fixed in [5.0.0-beta.5](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-beta.5)
