### ISSUE TITLE
Cannot add role to a member even I am the owner and bot is all Admin

### ISSUE THREAD

**Issue by pitzzahh** [DV8FromTheWorld/JDA#2410]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### What should happen
The bot should add a verified role to a user.

### My assumptions
- I was the second owner of the guild and the bot somehow affected by it?
- The adding role functionality works on new guild that I created

### Code Example for Reproduction Steps

```java
@Override
    public void onButtonInteraction(@NotNull ButtonInteractionEvent event) {
        final var ID = event.getButton().getId();
        final var MEMBER = event.getMember();
        if ("ok".equals(ID)) event.getInteraction().getMessage().delete().queue();
        else if ("verify-button".equals(ID)) {
            final var VERIFIED_ROLE = Objects.requireNonNull(event.getGuild(), "Cannot find verified role")
                    .getRolesByName("verified", false)
                    .stream()
                    .findAny();
            if (VERIFIED_ROLE.isPresent()) {
                log.info("Verified role is present");
                assert MEMBER != null;
                var isVerified = MEMBER.getRoles()
                        .stream()
                        .map(Role::getName)
                        .anyMatch(e -> VERIFIED_ROLE.get().getName().equals(e));
                messageUtil.getMessageBuilder().clear();
                if (isVerified) {
                    log.info("User {} is already verified", MEMBER.getUser().getAsTag());
                    message(false);
                }
                else {
                    log.info("User {} roles are", MEMBER.getRoles());
                    message(true);
                    event.getGuild().addRoleToMember(MEMBER, VERIFIED_ROLE.get()).queue();
                    log.info("User {} is verified", MEMBER.getUser().getAsTag());
                }
                event.getInteraction()
                        .replyEmbeds(messageUtil.getEmbedBuilder().build())
                        .setEphemeral(true)
                        .queue();
            } else log.error("Verified role is not present");
        }
    }

    private void message(boolean flag) {
        log.info("Message is being sent");
        messageUtil.getEmbedBuilder()
                .clear()
                .clearFields()
                .setColor(flag ? BLUE : RED)
                .setTitle(flag ? "Verified ✅" : "Already Verified")
                .setFooter(
                        format(
                                "This message will be automatically deleted on %s",
                                now(systemDefaultZone())
                                        .plusMinutes(1)
                                        .format(ofLocalizedTime(SHORT))
                        )
                );
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
@Bean
    public ShardManager shardManager() {
        log.info("Initializing ShardManager...");
        var builder = DefaultShardManagerBuilder.createDefault(tokenService.getToken());

        builder.setStatus(OnlineStatus.ONLINE)
                .enableIntents(GatewayIntent.MESSAGE_CONTENT)
                .enableIntents(GatewayIntent.GUILD_MEMBERS)
                .setActivity(Activity.listening("your messages 📩"));

        try {
            messageCheckerService.loadSwearWords();
        } catch (IOException e) {
            log.error(e.getMessage(), e);
            throw new RuntimeException(e);
        }

        builder.addEventListeners(
                new MessageListener(
                        messageCheckerService,
                        confessionService,
                        violationService,
                        commandsService,
                        categoryService,
                        channelService,
                        commandManager,
                        messageUtil,
                        gameService,
                        confession
                ),
                new ButtonListener(messageUtil),
                new SlashCommandListener(
                        new SlashCommandManager(
                                confessionService,
                                commandsService,
                                channelService,
                                jokesService,
                                gameService,
                                messageUtil,
                                httpConfig
                        )
                ),
                new MemberLogger(
                        new ChannelService(new ChannelsConfig()),
                        new MessageUtil()
                )
        );

        try {
            return builder.build();
        } catch (LoginException e) {
            log.error(e.getMessage(), e);
            throw new RuntimeException(e);
        }
    }
```

### Exception or Error

```yesyes
net.dv8tion.jda.api.exceptions.HierarchyException: Can't modify a role with higher or equal highest role than yourself! Role: R:verified(1008674782721617960)
	at net.dv8tion.jda.internal.entities.GuildImpl.checkPosition(GuildImpl.java:1882) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.entities.GuildImpl.addRoleToMember(GuildImpl.java:1551) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at tech.araopj.springpitzzahhbot.listeners.ButtonListener.onButtonInteraction(ButtonListener.java:76) ~[classes/:na]
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:131) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:83) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[JDA-5.0.0-alpha.17.jar:5.0.0-alpha.17]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar:na]
```

**Comment by pitzzahh** [comment]
I also kicked the bot and re added it and still gave me error

**Comment by MinnDevelopment** [comment]
As the error clearly states, the issue is that the role you are trying to assign is higher or equal in position to the bot's highest role. Whether the bot has administrator permissions is inconsequential, the hierarchy rule can only be bypassed by guild owners.
