### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by MrBeefchop** [DV8FromTheWorld/JDA#267]
I have implemented the source in my project and I have no errors, but when I want to test it I get this error:
I tried to use this JDA versions: JDA-2.2.1_353.jar, JDA-2.3.0_379
```
[13:01:29] [Server thread/ERROR]: Could not load 'plugins\Discord-MC.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/dv8tion/jda/entities/User
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/dv8tion/jda/entities/User
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.entities.User
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	... 6 more
```

**Comment by NachtRaben** [comment]
Latest JDA is 3.0BETA2_135, I'd say you should contact the plugin author to update that at some point >~>

**Comment by DinosParkour** [comment]
This shouldn't be related to any version issues, you're simply not compiling the jar file properly. How are you exporting your project?

**Comment by MrBeefchop** [comment]
I am exporting the Discord-MC project as a JAR File with eclipse.
Picture: https://imgur.com/a/CtTu8

**Comment by NachtRaben** [comment]
You can use maven/gradle to create a shaded plugin jar that include everything from the JDA with dependencies jar into your plugin, or you can find another way to shade all the JDA dependencies into your jar.

**Comment by MrBeefchop** [comment]
I tried to use maven, but I still get the error. Could you send me a tutorial how to create a shaded plugin that include everything from the JDA with dependencies?

**Comment by OutdatedVersion** [comment]
Be sure you're using the `maven-shade-plugin` whilst building that plugin. Here's [an example](https://github.com/OutdatedVersion/mineplex-api-java/blob/master/pom.xml#L54-L68) of using it.

**Comment by MinnDevelopment** [comment]
I request an update on this issue, has this been fixed or do you need more help? @MrBeefchop

**Comment by MinnDevelopment** [comment]
As this issue hasn't been updated the past 12 days, I am closing it.
Feel free to continue updating this issue and I will re-open it if I see the need for it
