### ISSUE TITLE
NPE on music connect.

### ISSUE THREAD

**Issue by Kodehawa** [DV8FromTheWorld/JDA#272]
Basically it randomly does this.

```
[10:58:25] [WritingThread/ERROR] [JDAAudioSocket]: An exception occurred
java.lang.NullPointerException: null
    at net.dv8tion.jda.core.requests.WebSocketClient.queueAudioConnect(WebSocketClient.java:777) ~[mantaro.jar:na]
    at net.dv8tion.jda.core.audio.AudioWebSocket.close(AudioWebSocket.java:361) ~[mantaro.jar:na]
    at net.dv8tion.jda.core.audio.AudioWebSocket.onDisconnected(AudioWebSocket.java:277) ~[mantaro.jar:na]
    at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:223) ~[mantaro.jar:na]
    at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3414) [mantaro.jar:na]
    at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3384) [mantaro.jar:na]
    at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3373) [mantaro.jar:na]
    at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:541) [mantaro.jar:na]
    at com.neovisionaries.ws.client.WritingThread.run(WritingThread.java:80) [mantaro.jar:na]

[11:44:42] [WritingThread/ERROR] [JDAAudioSocket]: An exception occurred
java.lang.NullPointerException: null
    at net.dv8tion.jda.core.audio.AudioWebSocket.close(AudioWebSocket.java:346) ~[mantaro.jar:na]
    at net.dv8tion.jda.core.audio.AudioWebSocket.onDisconnected(AudioWebSocket.java:277) ~[mantaro.jar:na]
    at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:223) ~[mantaro.jar:na]
    at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3414) [mantaro.jar:na]
    at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3384) [mantaro.jar:na]
    at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3373) [mantaro.jar:na]
    at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:541) [mantaro.jar:na]
    at com.neovisionaries.ws.client.WritingThread.run(WritingThread.java:80) [mantaro.jar:na]

[11:49:13] [ReadingThread/ERROR] [JDASocket]: An exception occurred
java.lang.NullPointerException: null
    at net.dv8tion.jda.core.audio.AudioConnection.<init>(AudioConnection.java:84) ~[mantaro.jar:na]
    at net.dv8tion.jda.core.handle.VoiceServerUpdateHandler.handleInternally(VoiceServerUpdateHandler.java:82) ~[mantaro.jar:na]
    at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38) ~[mantaro.jar:na]
    at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:722) [mantaro.jar:na]
    at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:460) [mantaro.jar:na]
    at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352) [mantaro.jar:na]
    at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262) [mantaro.jar:na]
    at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240) [mantaro.jar:na]
    at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965) [mantaro.jar:na]
    at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748) [mantaro.jar:na]
    at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110) [mantaro.jar:na]
    at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66) [mantaro.jar:na]

```

**Comment by DV8FromTheWorld** [comment]
Please do me a favor and try using `3.0.BETA2_141` and see if you still get these errors.

**Comment by Kodehawa** [comment]
I haven't gotten those in 3 days so I think it's completely fixed. Thanks.
