### ISSUE TITLE
Exception on AudioConnection

### ISSUE THREAD

**Issue by dscalzi** [DV8FromTheWorld/JDA#377]
When the bot connects to audio this exception is thrown.

    Exception in thread "JDA AudioConnection Guild: 98469309352775680 Ready Thread" java.lang.UnsatisfiedLinkError: /tmp/jna--339822521/jna2349819471283550059.tmp: /lib/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/jna--339822521/jna2349819471283550059.tmp)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at tomp2p.opuswrapper.Opus.<clinit>(Opus.java:29)
	at net.dv8tion.jda.core.audio.AudioConnection.setupSendSystem(AudioConnection.java:239)
	at net.dv8tion.jda.core.audio.AudioConnection.access$200(AudioConnection.java:51)
	at net.dv8tion.jda.core.audio.AudioConnection$1.run(AudioConnection.java:127)
    Jun 16, 2017 5:11:33 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
    WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added

This exception was thrown when hosting on a headless linux box, it does not occur on windows. Running 
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

**Comment by dscalzi** [comment]
Not something wrong with the API, gonna close this.
