### ISSUE TITLE
NPE when guild creating

### ISSUE THREAD

**Issue by hlaaftana** [DV8FromTheWorld/JDA#448]
Using 3.2.0_254. Bot only has 2 guilds

```
[23:26:54] [Fatal] [JDASocket]: Completed the setup for Guild: G:ff(337012901657182208) without matching id in ReadyHandler cache
[23:26:54] [Fatal] [JDASocket]: Encountered an exception:
[23:26:54] [Fatal] [JDASocket]: java.lang.NullPointerException
	at net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:193)
	at net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$91(GuildCreateHandler.java:44)
	at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:297)
	at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:38)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:856)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:559)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:890)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:272)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:992)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:751)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
```

**Comment by MinnDevelopment** [comment]
You are using an outdated version of org.json that is missing JSONArray#forEach. Please update your dependencies.

**Comment by bradyhedrick** [comment]
> 

how do you do that?
