### ISSUE TITLE
Completed the setup for Guild without matching id in ReadyHandler cache

### ISSUE THREAD

**Issue by exception** [DV8FromTheWorld/JDA#454]
This was already reported a while back, however it's still happening:
```java
[11:39:16] [Fatal] [JDASocket]: Completed the setup for Guild: G:MyGuild(MyToken) without matching id in ReadyHandler cache
[11:39:16] [Fatal] [JDASocket]: Encountered an exception:
[11:39:16] [Fatal] [JDASocket]: java.lang.NullPointerException
        at net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:193)
        at net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$97(GuildCreateHandler.java:44)
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:298)
        at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:38)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:876)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:573)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:910)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

I am using the latest version of JDA:
```xml
<dependency>
    <groupId>net.dv8tion</groupId>
    <artifactId>JDA</artifactId>
    <version>3.3.0_260</version>
</dependency>
```

**Comment by MinnDevelopment** [comment]
This was already answered when it was reported. #448
