### ISSUE TITLE
Received a channel for a guild that isn't a text or voice channel

### ISSUE THREAD

**Issue by NNowakowski** [DV8FromTheWorld/JDA#463]
Hello everyone!
Since yesterday my Discord bot suddenly stopped working.
Looking at the log files, the bot seemingly throws the following error:

```java
[11:16:28] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[{"allow":0,"deny":2048,"id":"264445053596991498","type":"role"}],"nsfw":false,"parent_id":null,"name":"Information","position":0,"id":"355950354975686657","type":4}
```

This message repeats a few times, every time with different information.

Further down there's also some stacktrace:

```java
[11:16:30] [Fatal] [JDASocket]: java.lang.RuntimeException: Got permission_override for unknown channel with id: 355950354975686657
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuildChannelPass(EntityBuilder.java:394)
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuildSecondPass(EntityBuilder.java:319)
        at net.dv8tion.jda.core.handle.GuildMembersChunkHandler.handleInternally(GuildMembersChunkHandler.java:61)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:738)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:475)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

Does anyone have an idea on what is happening?

**Comment by duncte123** [comment]
that is happening because you are not on the latest version, use vesion 3.3.0_265
