### ISSUE TITLE
ReadyCache Null Pointer after loading Guilds

### ISSUE THREAD

**Issue by Aion253** [DV8FromTheWorld/JDA#466]
I was having trouble with JDA 3.1.1 failing to connect and thusly switched to 3.3.0. I have however once again run into an issue. While I can again login successfully I get the following error after I connect to the Server: 

Just fyi anything enclosed here in <> was my intention to not give you actual information about my server.

`[13:17:39] [Fatal] [JDASocket]: Completed the setup for Guild: G:<guild_name>(<numbers>) without matching id in ReadyHandler cache
[13:17:39] [Fatal] [JDASocket]: Encountered an exception:
[13:17:39] [Fatal] [JDASocket]: java.lang.NullPointerException
	at net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:193)
	at net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$0(GuildCreateHandler.java:44)
	at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:298)
	at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:38)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:876)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:573)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:910)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)`

In addition I get this once for each channel on the server when I connect:
`[13:17:39] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel (ChannelPass). JSON: {"permission_overwrites":[{"allow":0,"deny":1049600,"id":"<numbers>","type":"role"},{"allow":1049600,"deny":0,"id":"<numbers>","type":"role"}],"nsfw":false,"parent_id":null,"name":"<name>","position":4,"id":"<numbers>","type":4}
[13:17:39] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: <numbers>`

From the error I can surmise that it a JDA internal error not caused by my code and I don't know what I can do to fix it. I am NOT using gradle or maven.

**Comment by MinnDevelopment** [comment]
The NPE has already been addressed in #463 and #448 .
The second error comes because you are on an outdated JDA version that does not handle the newly introduced channel categories.

**Comment by Aion253** [comment]
I'm literally on the newest version of JDA... What's good.

**Comment by MinnDevelopment** [comment]
The error you are receiving is impossible to get on latest JDA.

**Comment by kantenkugel** [comment]
Just to add: the last build is build 266 as of now

**Comment by Aion253** [comment]
I was running 266, however I had separately added my own out of date instances of the OkHTTP3 and the json which were both causing separate issues. I hadn't thought about that they would cause issues with the installation. I've removed them and modified my code slightly.

**Comment by kantenkugel** [comment]
@Aion253 problem fixed now?

**Comment by Aion253** [comment]
Now that I've removed the extra libraries yes, it is working.

**Comment by Sanduhr32** [comment]
NPE in ready has been reported many times by people because their JSON dependency was older than the build from 2016.

**Comment by spinywind** [comment]
Im having this issue too on eclipse. Im not using a maven project though, I imported an external JAR and im getting this error:

[23:25:02] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel.

JAR im using: https://github.com/DV8FromTheWorld/JDA/releases

**Comment by MinnDevelopment** [comment]
As mentioned in the release the latest build is on the build server http://home.dv8tion.net:8080/job/JDA/

**Comment by kantenkugel** [comment]
@MinnDevelopment see why i don't like the release page?^^
