### ISSUE TITLE
java.lang.InterruptedException at end of an audio stream

### ISSUE THREAD

**Issue by Seres67** [DV8FromTheWorld/JDA#485]
```java
net.dv8tion.jda.core.requests.WebSocketClient - Encountered an Exception 
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at net.dv8tion.jda.core.requests.WebSocketClient.queueAudioDisconnect(WebSocketClient.java:1117)
	at net.dv8tion.jda.core.audio.AudioWebSocket.close(AudioWebSocket.java:450)
	at net.dv8tion.jda.core.audio.AudioConnection.close(AudioConnection.java:226)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:139)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:130)
	at audio.AudioListener.nextTrack(AudioListener.java:34)
	at audio.AudioListener.onTrackEnd(AudioListener.java:42)
	at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:70)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.dispatchEvent(AudioPlayer.java:295)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.handleTerminator(AudioPlayer.java:217)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provideDirectly(AudioPlayer.java:197)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:167)
	at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:162)
	at audio.AudioHandler.canProvide(AudioHandler.java:22)
	at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:607)
	at net.dv8tion.jda.core.audio.factory.DefaultSendSystem.lambda$start$61(DefaultSendSystem.java:57)
	at java.lang.Thread.run(Thread.java:745)
```

Here is the full exception I get at the end of an audiostream.

canProvide() & provide20MsAudio()
```java
@Override
    public boolean canProvide()
    {
        if (lastFrame == null)
            lastFrame = audioPlayer.provide();
        return lastFrame != null;
    }

    @Override
    public byte[] provide20MsAudio()
    {
        if (lastFrame == null)
            lastFrame = audioPlayer.provide();
        byte[] data = lastFrame != null ? lastFrame.data : null;
        lastFrame = null;
        return data;
    }
```

How can I fix this ?

**Comment by MinnDevelopment** [comment]
The events of `AudioEventAdapter` operate on the audio-send thread which is interrupted by `closeAudioConnection`.
It is no longer possible to modify the audio connection in player events such as `onTrackEnd`. You have to close/open connections on a separate thread.

**Comment by Seres67** [comment]
Okay, thanks for the help.
