### ISSUE TITLE
NoSuchMethod error in org.json; Not matching guild ID in ReadyHandler cache

### ISSUE THREAD

**Issue by DiamondIceNS** [DV8FromTheWorld/JDA#487]
Stacktrace:
```
[13:52:25] [Info] [JDASocket]: Connected to WebSocket
[13:52:25] [Fatal] [JDASocket]: Encountered an exception:
[13:52:25] [Fatal] [JDASocket]: java.lang.NoSuchMethodError: org.json.JSONArray.iterator()Ljava/util/Iterator;
	at net.dv8tion.jda.core.requests.WebSocketClient.updateTraces(WebSocketClient.java:124)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:631)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

[13:52:25] [Fatal] [JDASocket]: Encountered an exception:
[13:52:25] [Fatal] [JDASocket]: java.lang.NoSuchMethodError: org.json.JSONArray.iterator()Ljava/util/Iterator;
	at net.dv8tion.jda.core.requests.WebSocketClient.updateTraces(WebSocketClient.java:124)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:895)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:603)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:944)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

[13:52:25] [Fatal] [JDASocket]: Completed the setup for Guild: [[REDACTED]] without matching id in ReadyHandler cache
[13:52:25] [Fatal] [JDASocket]: Encountered an exception:
[13:52:25] [Fatal] [JDASocket]: java.lang.NullPointerException
	at net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:193)
	at net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$112(GuildCreateHandler.java:44)
	at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:302)
	at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:38)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:910)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:603)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:944)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

I'm using JDA version `3.3.0_266`. Regarding the NullPointer exception, I tried the fix suggested in #421 but nothing changed. I am compiling with Gradle, the relevant portion of which looks like this:

```
    compile group: 'org.spigotmc', name: 'spigot-api', version: '1.11.2-R0.1-SNAPSHOT'
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib', version: '1.0.0-rc-1036'
    compile group: 'net.dv8tion', name: 'JDA', version: '3.3.0_266'
    compile group: 'com.michaelwflaherty', name: 'cleverbotapi', version: '1.0.1'
    compile group: 'org.pegdown', name:'pegdown', version: '1.6.0'
    compile group: 'org.json', name: 'json', version: '20160810'
```
Just to check, I tried compiling with version `20170516` of org.json and I received the same errors.

Researching these same errors in other closed issues tells me that they shouldn't be possible with these versions of JDA and org.json, so apparently something isn't getting through. I assume there is a conflict somewhere, but I don't know where. I'm using IntelliJ IDEA for this project, and in the External Libraries pane, it shows the correct versions of libraries are downloading, and I'm using Shadow to ensure all dependencies are packing into the final jar. All the signs I see point to the fact that this should be working, yet here we are.

**Comment by kantenkugel** [comment]
Huh... i thought that "bug" was something from maven only... can you check which version of org.json is actually included? (via IDE or some gradle command)

**Comment by natanbc** [comment]
1) Update JDA
2) Try relocating org.json, it appears something else loaded an older version at runtime before your code ran (Most likely spigot)

**Comment by firefox2150** [comment]
I'm getting the same sort of errors, and I'm trying to figure out what could be causing it.  I manually updated org.json, jda, and neovisionaries in Maven to no avail.

**Comment by kantenkugel** [comment]
The only thing i can say is that `org.json` version `20170516 ` definately has `JSONArray#iterator()` (looked at source.jar from maven)

**Comment by firefox2150** [comment]
Managed to fix my issue.  Removed a couple of unneeded libraries that Maven was pulling, and that seems to have solved it in my program.  I have a feeling that natanbc is correct, that something is trying to use an older version of org.json that doesn't have the JSONArray.iterator()

**Comment by DiamondIceNS** [comment]
@natanbc Update JDA to which version? As far as I can tell, 266 is the latest build. The latest build on the releases page is at least 10 versions behind that, even; I don't know where to look to find the latest release version of JDA.

Also I'm not entirely sure what you mean by "relocating". Clearly there's a dependency clash, but I don't know exactly how to solve it. Perhaps this is a personal problem of mine and isn't in the scope of your issues.

**Comment by MinnDevelopment** [comment]
You can find the latest version in the README and on every release with this tag 

![image](https://i.imgur.com/34dQD6V.png)

**Comment by MinnDevelopment** [comment]
You can relocate using the shadow plugin of gradle as follows
```gradle
shadowJar {
    relocate 'org.json' 'my.package.org.json'
}
```
In addition you can print a dependency tree using gradle with the `dependencies` task.

**Comment by MinnDevelopment** [comment]
This seems to be resolved.

**Comment by DiamondIceNS** [comment]
My apologies for leaving you hanging, I haven't been able to touch the relevant project until just now.

Yes, the suggested fixes seem to have resolved the issue. Thank you for your clarity of explanation and patience with my ineptitude.
