### ISSUE TITLE
InterruptedException when AudioManager#closeAudioConnection()

### ISSUE THREAD

**Issue by Mon-chi** [DV8FromTheWorld/JDA#503]
InterruptedException is occurred when AudioManager#closeAudioConnection() run.
I call closeAudioConnection() in AudioEventAdapter#onTrackEnd() (LavaPlayer's class).

```
[18:38:37] [Fatal] [JDASocket]: Encountered an exception:
[18:38:37] [Fatal] [JDASocket]: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at net.dv8tion.jda.core.requests.WebSocketClient.queueAudioDisconnect(WebSocketClient.java:1114)
	at net.dv8tion.jda.core.audio.AudioWebSocket.close(AudioWebSocket.java:450)
	at net.dv8tion.jda.core.audio.AudioConnection.close(AudioConnection.java:226)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:139)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:130)
	at io.monchi.pucheen.audio.AudioHandler.onTrackEnd(AudioHandler.kt:45)
	at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:70)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.dispatchEvent(AudioPlayer.java:295)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.handleTerminator(AudioPlayer.java:217)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provideDirectly(AudioPlayer.java:197)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:167)
	at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:162)
	at io.monchi.pucheen.audio.AudioHandler.canProvide(AudioHandler.kt:56)
	at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:607)
	at net.dv8tion.jda.core.audio.factory.DefaultSendSystem.lambda$start$59(DefaultSendSystem.java:57)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kantenkugel** [comment]
This was already answered. Please take a look at #485

**Comment by Mon-chi** [comment]
Thank you for quick response! The problem solved.
