### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by PixelHamster** [DV8FromTheWorld/JDA#511]
```
17:03:57.952 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.requests.WebSocketClient - Got an unexpected error. Please redirect following message to the devs:
        VOICE_STATE_UPDATE -> {"self_deaf":false,"user_id":"363361861640388608","deaf":false,"session_id":"de235accd31619a7adec0cfd4287bd2f","mute":false,"suppress":false,"self_video":false,"self_mute":false,"channel_id":"365091241198616577"}
17:03:57.956 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.requests.WebSocketClient - Encountered an Exception
net.dv8tion.jda.core.exceptions.AccountTypeException: The current AccountType is not valid for the attempted action. Required AccountType: CLIENT
        at net.dv8tion.jda.core.entities.impl.JDAImpl.asClient(JDAImpl.java:473) ~[NCSBot-1.0-all.jar:?]
        at net.dv8tion.jda.core.handle.VoiceStateUpdateHandler.handleCallVoiceState(VoiceStateUpdateHandler.java:211) ~[NCSBot-1.0-all.jar:?]
        at net.dv8tion.jda.core.handle.VoiceStateUpdateHandler.handleInternally(VoiceStateUpdateHandler.java:58) ~[NCSBot-1.0-all.jar:?]
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37) ~[NCSBot-1.0-all.jar:?]
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:969) [NCSBot-1.0-all.jar:?]
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:661) [NCSBot-1.0-all.jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352) [NCSBot-1.0-all.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260) [NCSBot-1.0-all.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238) [NCSBot-1.0-all.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963) [NCSBot-1.0-all.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746) [NCSBot-1.0-all.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [NCSBot-1.0-all.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [NCSBot-1.0-all.jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [NCSBot-1.0-all.jar:?]
```
I got this error twice and it is a music bot that plays music when a user joins a specific channel.

**Comment by kantenkugel** [comment]
This is due to some discord bug that got introduced with their new feature that allows you to call non-friends. The bug is that this feature currently also affects bots (users can call bots). 
I will probably write a quick fix that ignores that kind of voice update while this discord bug exists.

In the meantime, you can just ignore this error as there is nothing bad happening

**Comment by kantenkugel** [comment]
@PixelHamster when did that error last occur for you? Today?

**Comment by PixelHamster** [comment]
I don't know i wasn't home for 3 days xD.

**Comment by kantenkugel** [comment]
According to discord staff, this bug should've been fixed recently. Im assuming that this happened prior.
Not gonna fix due to bug being resolved.
If you get this error again, please let us know because then its something different

**Comment by MinnDevelopment** [comment]
This was an error on discord's end allowing users to call bots which was unintended.
The error has been resolved as of yesterday according to @jhgg
