### ISSUE TITLE
Completed the setup for Guild without matching id in Ready Handler cache - no trace

### ISSUE THREAD

**Issue by napstr** [DV8FromTheWorld/JDA#512]
```
17:07:17.292 [JDA [1 / 2] MainWS-ReadThread] [ERROR] n.d.j.core.requests.WebSocketClient - Completed the setup for Guild: G:SNIP(SNIP) without matching id in Ready Handler cache
```

Got this error on 3.3.1_286 , while booting up shards.
There is no other log or stack trace to indicate the reason, just a bunch of these in the debuglog right before that:

```
17:07:09.482 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
17:07:10.533 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching MESSAGE_DELETE event during init!
17:07:10.932 [JDA [1 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
17:07:11.543 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching MESSAGE_CREATE event during init!
17:07:11.544 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
17:07:11.572 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
17:07:14.197 [JDA [1 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
17:07:15.113 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching MESSAGE_CREATE event during init!
17:07:15.113 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
17:07:15.358 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching MESSAGE_CREATE event during init!
17:07:15.427 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
17:07:15.427 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
17:07:15.460 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
17:07:17.256 [JDA [0 / 2] MainWS-ReadThread] [DEBUG] n.d.j.core.requests.WebSocketClient - Caching PRESENCE_UPDATE event during init!
```

**Comment by MinnDevelopment** [comment]
Is this consistent and reproducible?

**Comment by napstr** [comment]
Don't think so, didn't get that during a restart yesterday.  I'll try booting (a copy) of the bot up and down a few times to try and reproduce and also check whether the guild that caused this is still present, and report back.

**Comment by napstr** [comment]
Guild is not present anymore. No luck with a bunch of starts, didn't get any errors.

**Comment by napstr** [comment]
Just happened again after a reconnect (running JDA build is hotfix-zlib branch).

https://wastebin.party/yawipuzeqo.css

Debug log has those same Caching Presence lines (about a hundred per shard reconnecting) as shown in the OP, didn't see any other suspicious things.

**Comment by MinnDevelopment** [comment]
Is that consistent on shard 0?

**Comment by napstr** [comment]
I have only observed these two incidents, might be chance.
One thing to note is that I cache some guild data on guild join, and this guild is not in the database, which means the GuildJoin event was missed (probably happened during the reconnect).

**Comment by MinnDevelopment** [comment]
I think I know what's happening:
1) Disconnect
2) Connect
3) READY -> stores guild ids to build
4) GUILD_CREATEs for those guild ids
5) GUILD_CREATE for new joined guild, no matching id -> error to console

**Comment by MinnDevelopment** [comment]
Does this still happen on 48bc751?

**Comment by napstr** [comment]
Yes still does (on 305). Got two of these in the aftermath of the discord outage earlier.

**Comment by napstr** [comment]
On the websocket enhancement branch: 9f766395228a56ef553a0d181dab69cdadf67765

```
Completed the setup for Guild: G:Taz Studio(404660633095766027) without matching id in ReadyHandler cache
   at net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:191)
    at net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$0(GuildCreateHandler.java:45)
    at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:351)
    at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:39)
    at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
    at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1042)
    at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:896)
    at net.dv8tion.jda.core.requests.WebSocketClient.handleBinary(WebSocketClient.java:1123)
```
jda debug level log filtered by the shard:
[jda.log](https://github.com/DV8FromTheWorld/JDA/files/1814762/jda.log)
