### ISSUE TITLE
Error when trying to join voice channel

### ISSUE THREAD

**Issue by nathanthesnooper** [DV8FromTheWorld/JDA#532]
Connect to voice channel line:
```
event.getGuild().getAudioManager().openAudioConnection(userState.getChannel());
```

Log:
```
[main] INFO net.dv8tion.jda.core.JDA - Login Successful!
[ReadingThread] INFO net.dv8tion.jda.core.requests.WebSocketClient - Connected to WebSocket
[ReadingThread] INFO net.dv8tion.jda.core.JDA - Finished Loading!
[INFO] Loading config: /home/nathanthesnooper/workspace/SinisterBot/config.txt
[main] WARN Settings - Failed to load server settings: java.nio.file.NoSuchFileException: serversettings.json
[main] INFO net.dv8tion.jda.core.JDA - Login Successful!
[ReadingThread] INFO net.dv8tion.jda.core.requests.WebSocketClient - Connected to WebSocket
[ReadingThread] ERROR net.dv8tion.jda.core.requests.WebSocketClient - Encountered IDENTIFY (OP 2) Rate Limit! Waiting 5 seconds before trying again!
[ReadingThread] WARN net.dv8tion.jda.core.requests.WebSocketClient - Attempting to reconnect!
[ReadingThread] INFO net.dv8tion.jda.core.requests.WebSocketClient - Connected to WebSocket
[ReadingThread] INFO net.dv8tion.jda.core.JDA - Finished Loading!

// This is when I play a song/join voice chat

[ReadingThread] ERROR net.dv8tion.jda.core.managers.AudioManager - An unknown error occurred while attempting to setup JDA's audio system!
[ReadingThread] ERROR net.dv8tion.jda.core.managers.AudioManager - Encountered an Exception 
java.lang.NoSuchFieldError: RESOURCE_PREFIX
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.init(AudioManagerImpl.java:354)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.<init>(AudioManagerImpl.java:71)
	at net.dv8tion.jda.core.entities.impl.GuildImpl.getAudioManager(GuildImpl.java:466)
	at com.jagrosh.jmusicbot.commands.MusicCommand.execute(MusicCommand.java:79)
	at com.jagrosh.jdautilities.commandclient.Command.run(Command.java:319)
	at com.jagrosh.jdautilities.commandclient.impl.CommandClientImpl.onMessageReceived(CommandClientImpl.java:545)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:404)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:128)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:978)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:666)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:247)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:231)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:209)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:744)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:604)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:100)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:59)
[ReadingThread] INFO net.dv8tion.jda.core.managers.AudioManager - Audio System encountered problems while loading, thus, is disabled.
[ReadingThread] ERROR net.dv8tion.jda.core.JDA - One of the EventListeners had an uncaught exception
[ReadingThread] ERROR net.dv8tion.jda.core.JDA - Encountered an Exception 
java.lang.UnsupportedOperationException: Sorry! Audio is disabled due to an internal JDA error! Contact Dev!
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.openAudioConnection(AudioManagerImpl.java:85)
	at com.jagrosh.jmusicbot.commands.MusicCommand.execute(MusicCommand.java:79)
	at com.jagrosh.jdautilities.commandclient.Command.run(Command.java:319)
	at com.jagrosh.jdautilities.commandclient.impl.CommandClientImpl.onMessageReceived(CommandClientImpl.java:545)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:404)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:128)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:978)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:666)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:247)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:231)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:209)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:744)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:604)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:100)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:59)
```

**Comment by MinnDevelopment** [comment]
These exceptions don't come alone, there has to be another exception further up in the logs that explains this.

**Comment by nathanthesnooper** [comment]
I added the whole log, hopefully that helps

**Comment by MinnDevelopment** [comment]
You have an incompatible version of [JNA](https://github.com/java-native-access)

**Comment by nathanthesnooper** [comment]
Does JNA have linux support?

**Comment by MinnDevelopment** [comment]
Yes

**Comment by nathanthesnooper** [comment]
Is 3.0.9 The latest version? (It is on maven repo)

**Comment by nathanthesnooper** [comment]
Oh, sorry I just found it was moved

**Comment by nathanthesnooper** [comment]
I am getting this error now
```
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.natives.NativeResourceHolder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
```
(Should I open another issue or keep it here?)

**Comment by natanbc** [comment]
You're missing dependencies, how did you add lavaplayer to your project?

**Comment by nathanthesnooper** [comment]
I am using `lavaplayer-1.2.9.jar` for the library, is this outdated? I don't see NativeResourceHolder in GitHub

**Comment by natanbc** [comment]
There's no lavaplayer jar with all the dependencies, to get them all you'll need gradle or maven

**Comment by nathanthesnooper** [comment]
http://i.imgur.com/QUiDV0r.png I manually installed all the dependencies

**Comment by MinnDevelopment** [comment]
Please consider using maven/gradle.

**Comment by DV8FromTheWorld** [comment]
I am closing this as this is no longer an issue related to JDA.
If you are still having issues with `lavaplayer`, please open an issue in that repository.
