### ISSUE TITLE
Unknowkn Error. JDA Error maybe?

### ISSUE THREAD

**Issue by rrphacker** [DV8FromTheWorld/JDA#553]
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

[19:14:35] [INFO] [net.dv8tion.jda.core.JDA]: Login Successful!
[19:14:35] [INFO] [net.dv8tion.jda.core.requests.WebSocketClient]: Connected to WebSocket

[19:15:21] [ERROR] [net.dv8tion.jda.core.requests.WebSocketClient]: Encountered an Exception: 
org.json.JSONException: JSONObject["d"] is not a JSONObject.
	at org.json.JSONObject.getJSONObject(JSONObject.java:640)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:938)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:685)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1053)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

[19:17:12] [INFO] [net.dv8tion.jda.core.JDA]: Finished Loading!
```

**Comment by MinnDevelopment** [comment]
Please read and fill out the issue template.
