### ISSUE TITLE
deleteMessages does not work for messages older than 2 weeks

### ISSUE THREAD

**Issue by cab404** [DV8FromTheWorld/JDA#556]
deleteMessages does not delete for messages older than 2 weeks, though deleteMessage (and discord) does work for those. 

It fails with this exception:
```
java.lang.IllegalArgumentException: Message Id provided was older than 2 weeks. Id: 380079703991779328
        at net.dv8tion.jda.core.utils.Checks.check(Checks.java:27)
        at net.dv8tion.jda.core.entities.impl.TextChannelImpl.deleteMessagesByIds(TextChannelImpl.java:132)
        at net.dv8tion.jda.core.entities.impl.TextChannelImpl.deleteMessages(TextChannelImpl.java:116)
```

**Comment by WalshyDev** [comment]
This is a Discord thing, please refer to https://github.com/discordapp/discord-api-docs/issues/208

**Comment by cab404** [comment]
didn't know, thanks @WalshyDev
