### ISSUE TITLE
Unable to load library

### ISSUE THREAD

**Issue by SirYwell** [DV8FromTheWorld/JDA#590]
I tried to build a bot which can play audio files using lavaplayer, but JDA throws following error everytime I try to play music: 
```
ERROR net.dv8tion.jda.core.audio.AudioConnection - Uncaught exception in Audio ready-thread
java.lang.UnsatisfiedLinkError: Unable to load library '/natives/win32-x86/libopus.dll': JNA native support (win32-x86//natives/win32-x86/libopus.dll.dll) not found in resource path
```

The given .dll file is packed in the jar in `natives/win32-x86` so it exists. If I delete the file, it throws an FileNotFoundException on startup. I'm using version 3.4.0_323 and I have no clue what's the problem.

**Comment by kantenkugel** [comment]
The question is why your jvm preprends "win32-x86/" to the resource path...

**Comment by kantenkugel** [comment]
What OS and what Java version are you using?

**Comment by SirYwell** [comment]
Due to compatibility reasons I need to use Java 32 bit on Windows 10 64 bit

**Comment by natanbc** [comment]
Try running the code again with the `jna.debug_load` system property set to true (to get extra debug info)

**Comment by SirYwell** [comment]
```
[JDA AudioConnection Guild: 252460850890145802 Ready Thread] ERROR net.dv8tion.jda.core.audio.AudioConnection - Uncaught exception in Audio ready-thread
java.lang.UnsatisfiedLinkError: Unable to load library '/natives/win32-x86/libopus.dll': JNA native support (win32-x86//natives/win32-x86/libopus.dll.dll) not found in resource path (sample-java-client.jar)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:220) ~[sample-java-client.jar:2.8.5]
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:322) ~[sample-java-client.jar:2.8.5]
        at com.sun.jna.Library$Handler.<init>(Library.java:142) ~[sample-java-client.jar:2.8.5]
        at com.sun.jna.Native.loadLibrary(Native.java:387) ~[sample-java-client.jar:2.8.5]
        at com.sun.jna.Native.loadLibrary(Native.java:366) ~[sample-java-client.jar:2.8.5]
        at tomp2p.opuswrapper.Opus.<clinit>(Opus.java:29) ~[sample-java-client.jar:2.8.5]
        at net.dv8tion.jda.core.audio.AudioConnection.setupSendSystem(AudioConnection.java:266) ~[sample-java-client.jar:2.8.5]
        at net.dv8tion.jda.core.audio.AudioConnection.lambda$ready$0(AudioConnection.java:130) ~[sample-java-client.jar:2.8.5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

That's the whole stacktrace I got.

**Comment by MinnDevelopment** [comment]
This sounds like an issue with your JNA version.

**Comment by MinnDevelopment** [comment]
Any update on this?

**Comment by SirYwell** [comment]
Sorry I was busy during the week. Seems like the version was the problem actually. JNA was provided by another dependency so I had to overwrite this. Now it works fine. Thanks for your help.
