### ISSUE TITLE
WebSocketClient -> NoSuchMethodError: org.json.JSONArray.iterator

### ISSUE THREAD

**Issue by avurro** [DV8FromTheWorld/JDA#746]
Hi guys,

I saw all the issues, but no solution worked.
I have excluded org.json from the addiction and explicitly added the latest version.
Below the pom.xml:
```xml
<dependency>
   <groupId>net.dv8tion</groupId>
   <artifactId>JDA</artifactId>
   <version>3.7.1_399</version>
   <type>jar</type>
   <scope>compile</scope>
   <exclusions>
         <exclusion>
	    <groupId>club.minnced</groupId>
	    <artifactId>opus-java</artifactId>
	 </exclusion>
	 <exclusion>
	    <groupId>org.json</groupId>
	    <artifactId>json</artifactId>
	 </exclusion>
   </exclusions>
</dependency>
<dependency>
	<groupId>org.json</groupId>
	<artifactId>json</artifactId>
	<version>20180813</version>
</dependency>
```
I get the following error:
```
[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] ERROR WebSocketClient - There was an error in the WebSocket connection
java.lang.NoSuchMethodError: org.json.JSONArray.iterator()Ljava/util/Iterator;
	at net.dv8tion.jda.core.requests.WebSocketClient.updateTraces(WebSocketClient.java:162)
	at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:958)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:908)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1101)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```
How can I solve this?

**Comment by Sanduhr32** [comment]
You have to update your org.json dependency. Please ask in the support guild next time, due the github tracker is for feature requests and bug reports.

**Comment by kantenkugel** [comment]
Please refer to this issue for further details about the org.json incompatibility of yours: #716
