### ISSUE TITLE
AuditLog

### ISSUE THREAD

**Issue by YukioKeno** [DV8FromTheWorld/JDA#783]
### Issue Type

- [X ] Bug Report
- [ ] Feature Request

### Description

Dieser Code wird in meinem onGuildMessageRecive Listener aufgerufen:
```java
AuditLogPaginationAction logs = event.getGuild().getAuditLogs();
        for (AuditLogEntry entry : logs)
        {
            System.out.println("Type: " + entry.getType() + "\nReason: " + entry.getReason());
        }
```

Wenn ich also eine Nachricht schreibe und der oben angegebene Code ausgeführt wird bekomme ich folgende Fehlermeldung:
```
21.09.18 17:28:56 ERROR - Requester system encountered an internal error
java.lang.NoSuchMethodError: org.json.JSONArray.toList()Ljava/util/List;
	at net.dv8tion.jda.core.entities.EntityBuilder.createAuditLogChange(EntityBuilder.java:1340)
	at net.dv8tion.jda.core.entities.EntityBuilder.createAuditLogEntry(EntityBuilder.java:1314)
	at net.dv8tion.jda.core.requests.restaction.pagination.AuditLogPaginationAction.handleResponse(AuditLogPaginationAction.java:229)
	at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:184)
	at net.dv8tion.jda.core.requests.Requester.execute$$$capture(Requester.java:225)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116)
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:344)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
21.09.18 17:28:56 ERROR - One of the EventListeners had an uncaught exception
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.json.JSONArray.toList()Ljava/util/List;
	at net.dv8tion.jda.core.requests.RestAction.complete(RestAction.java:446)
	at net.dv8tion.jda.core.requests.RestAction.complete(RestAction.java:399)
	at net.dv8tion.jda.core.requests.restaction.pagination.PaginationAction.getNextChunk(PaginationAction.java:645)
	at net.dv8tion.jda.core.requests.restaction.pagination.PaginationAction.access$000(PaginationAction.java:83)
	at net.dv8tion.jda.core.requests.restaction.pagination.PaginationAction$PaginationIterator.hasNext(PaginationAction.java:672)
	at listeners.messageListener.onGuildMessageReceived(messageListener.java:47)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:380)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:95)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:994)
	at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:892)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:871)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1029)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.json.JSONArray.toList()Ljava/util/List;
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at net.dv8tion.jda.core.requests.RestAction.complete(RestAction.java:432)
	... 20 more
Caused by: java.lang.NoSuchMethodError: org.json.JSONArray.toList()Ljava/util/List;
	at net.dv8tion.jda.core.entities.EntityBuilder.createAuditLogChange(EntityBuilder.java:1340)
	at net.dv8tion.jda.core.entities.EntityBuilder.createAuditLogEntry(EntityBuilder.java:1314)
	at net.dv8tion.jda.core.requests.restaction.pagination.AuditLogPaginationAction.handleResponse(AuditLogPaginationAction.java:229)
	at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:184)
	at net.dv8tion.jda.core.requests.Requester.execute$$$capture(Requester.java:225)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116)
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:344)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
 ```

**Comment by YukioKeno** [comment]
Ich nutze übrigenz Version 3.8.0_427 vom JDA

**Comment by Sanduhr32** [comment]
Well it looks like you use an outdated version of org.json in your project. Please read issue #746 .

**Comment by MinnDevelopment** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.
