### ISSUE TITLE
java.lang.NoClassDefFoundError: net/dv8tion/jda/core/hooks/ListenerAdapter

### ISSUE THREAD

**Issue by iBuseWinner** [DV8FromTheWorld/JDA#864]
Hello. I'm trying to do JDA+minecraft plugin (Spigot), but I can't launch this bot. I have an error. I'm using JDA version 3.8.0 (jar). Help, please! :c
`[13:17:09 ERROR]: Error occurred while enabling AdminPanel v1.19.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/dv8tion/jda/core/hooks/ListenerAdapter
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_144]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_144]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_144]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_144]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_144]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_144]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_144]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at ru.ibusewinner.ap.AdminMain.onEnable(AdminMain.java:18) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:753) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:635) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.core.hooks.ListenerAdapter
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        ... 32 more`

**Comment by MisterFixx** [comment]
So... why are you posting this here?

**Comment by Devoxin** [comment]
The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.

**Comment by kantenkugel** [comment]
This isn't really an issue of JDA but rather how you use it (or rather not use it properly)

Please join the support server to get better help. This isn't really a JDA bug/feature request so this isn't the correct place to post in the first place (you didn't even use the template)
