### ISSUE TITLE
Android Studio trouble

### ISSUE THREAD

**Issue by WinnerSonX** [DV8FromTheWorld/JDA#947]
## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description
When i am trying to connect(JDA jda=new JdaBuilder("token").build())
i am getting error
I am try all posible ways to fix it, nothing works

```
    Process: com.winnersonx.myapplication, PID: 28373
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.winnersonx.myapplication/com.winnersonx.myapplication.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: No direct method <init>(Ljava/io/Reader;)V in class Lorg/json/JSONTokener; or its super classes (declaration of 'org.json.JSONTokener' appears in /system/framework/core-libart.jar)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: No direct method <init>(Ljava/io/Reader;)V in class Lorg/json/JSONTokener; or its super classes (declaration of 'org.json.JSONTokener' appears in /system/framework/core-libart.jar)
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:200)
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:295)
        at net.dv8tion.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:83)
        at net.dv8tion.jda.internal.JDAImpl.getGateway(JDAImpl.java:217)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:175)
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:168)
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:854)
        at com.winnersonx.myapplication.MainActivity.onCreate(MainActivity.java:19)
        at android.app.Activity.performCreate(Activity.java:7050)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6701) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
     Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: No direct method <init>(Ljava/io/Reader;)V in class Lorg/json/JSONTokener; or its super classes (declaration of 'org.json.JSONTokener' appears in /system/framework/core-libart.jar)
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:359)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1921)
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:186)
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:295) 
        at net.dv8tion.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:83) 
        at net.dv8tion.jda.internal.JDAImpl.getGateway(JDAImpl.java:217) 
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:175) 
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:168) 
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:854) 
        at com.winnersonx.myapplication.MainActivity.onCreate(MainActivity.java:19) 
        at android.app.Activity.performCreate(Activity.java:7050) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6701) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
     Caused by: java.lang.NoSuchMethodError: No direct method <init>(Ljava/io/Reader;)V in class Lorg/json/JSONTokener; or its super classes (declaration of 'org.json.JSONTokener' appears in /system/framework/core-libart.jar)
        at net.dv8tion.jda.api.requests.Response.lambda$static$0(Response.java:35)
        at net.dv8tion.jda.api.requests.-$$Lambda$Response$QOIpms-uPLlYMs_CvpMpp5WIFcI.apply(Unknown Source:2)
        at net.dv8tion.jda.api.requests.Response.parseBody(Response.java:194)
        at net.dv8tion.jda.api.requests.Response.parseBody(Response.java:172)
        at net.dv8tion.jda.api.requests.Response.get(Response.java:117)
        at net.dv8tion.jda.api.requests.Response.getObject(Response.java:101)
        at net.dv8tion.jda.api.utils.SessionControllerAdapter.lambda$getGateway$0(SessionControllerAdapter.java:83)
        at net.dv8tion.jda.api.utils.-$$Lambda$SessionControllerAdapter$dSsS4mpBdjy90WhjAR1NFXyoBck.apply(Unknown Source:4)
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleSuccess(RestActionImpl.java:243)
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:233)
        at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:188)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:227)

```

**Comment by MinnDevelopment** [comment]
JDA is not compatible with android and makes no attempts to support it.
